# <font color=#0099CC>**Notebook 3: Implementación de la Estrategia Momentum**</font>

En este notebook se implementa la lógica de inversión tipo MSCI Momentum:

1. **Universo**: activos que han formado parte del S&P 500 durante los últimos 13 meses (interpretación estricta: los 13 meses consecutivos - criterio de estabilidad y liquidez del universo).
2. **Momentum 12 y 6 meses** con retornos logarítmicos y lag de 1 mes (sin usar el mes actual - evita el look-ahead bias).
3. **Z-scores** transversales por mes para combinar ambas ventanas.
4. **Selección**: los 20 activos con mayor score compuesto y peso objetivo 5 % cada uno.

El resultado se guarda en `../outputs/selected_assets.csv` para el motor de backtest.

In [10]:
# Librerías
import os
import sys
from pathlib import Path

import pandas as pd
import numpy as np

# Permite importar utilidades compartidas desde la raíz del proyecto
project_root = Path.cwd().resolve()
if not (project_root / 'notebook_utils.py').exists():
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

from notebook_utils import configure_notebook_display, get_project_paths

# Configuración de visualización
configure_notebook_display(max_columns=None, max_rows=100)

BACKTEST_START = pd.Timestamp('2015-01-01')
BACKTEST_END = pd.Timestamp('2026-01-30')

# Rutas de entrada / salida centralizadas
PATHS = get_project_paths(project_root)
DATASETS_DIR = PATHS.datasets
OUTPUTS_DIR = PATHS.outputs

> <u>Nota</u>: Se aplica una arquitectura reutilizable basada en el módulo `notebook_utils.py` (rutas y configuración comunes). Esto reduce acoplamiento entre notebooks, mejora mantenibilidad y ayuda a mantener consistencia de estilo y documentación (PEP 8).

## <font color=#0099CC>**1. CARGA DE DATOS MENSUALES**</font>

### <font color=#336699>**1.1. Retornos logarítmicos y precios mensuales**</font>

Se cargan los retornos logarítmicos mensuales y los precios (open/close) al último día hábil de cada mes, generados en el Notebook 2, junto con el histórico del S&P 500 para construir el universo.

In [11]:
# Carga de datos mensuales y del histórico S&P 500

# Precios y retornos mensuales preparados en el Notebook 2
log_rets = pd.read_parquet(DATASETS_DIR / 'log_returns_monthly.parquet')
monthly_close = pd.read_parquet(DATASETS_DIR / 'monthly_close_prices.parquet')
monthly_open = pd.read_parquet(DATASETS_DIR / 'monthly_open_prices.parquet')

# Histórico completo con in_sp500 para construir el universo
sp500_hist = pd.read_parquet(
    DATASETS_DIR / 'sp500_history_deduplicated.parquet'
)  # histórico deduplicado (N2)
sp500_hist['date'] = pd.to_datetime(sp500_hist['date'])
sp500_hist = sp500_hist.set_index('date').sort_index()

print('> Datos cargados:')
print(f"  - log_returns_monthly: {log_rets.shape}")
print(f"  - monthly_close: {monthly_close.shape}")
print(f"  - monthly_open: {monthly_open.shape}")
print(f"  - sp500_history: {sp500_hist.shape}")

> Datos cargados:
  - log_returns_monthly: (146, 1234)
  - monthly_close: (147, 1234)
  - monthly_open: (147, 1234)
  - sp500_history: (7043936, 13)

> <u>Comentario</u>: Las dimensiones de los Parquet son coherentes: una fila por mes en retornos y precios mensuales, y el histórico S&P 500 en formato largo (fecha × símbolo) para el pivot de pertenencia al índice.

## <font color=#0099CC>**2. UNIVERSO DE INVERSIÓN (13 MESES)**</font>

### <font color=#336699>**2.1. Definición del universo**</font>

El universo abarca todos aquellos activos que han formado parte del S&P 500 durante los últimos 13 meses. Aquí se interpreta de forma **estricta**: un activo entra en el universo en el mes (t) solo si ha estado en el índice en **todos** los meses de la ventana (t-13 a t-1). Así se evita incluir entradas recientes con historial corto, introduciendo un criterio de estabilidad y liquidez del universo.

Para que en la primera fecha de rebalanceo (fin de enero 2015) esta ventana esté completa, el histórico de pertenencia al índice (in_sp500) no se recorta al periodo de backtest: se utiliza la serie completa del dataset del S&P 500, de modo que en cada mes haya 13 meses de historia disponibles.

In [12]:
# Universo de inversión: activos en el S&P 500 durante los últimos 13 meses

# Pivot diario de in_sp500 (0/1) por símbolo
in_sp500_daily = sp500_hist.pivot_table(
    index=sp500_hist.index,
    columns='symbol',
    values='in_sp500',
    aggfunc='last'
).astype(float)

# Pasar a frecuencia mensual (último valor de cada mes)
in_sp500_monthly = in_sp500_daily.resample('ME').last()

# Asegurar alineación temporal con los retornos mensuales: evitamos look-ahead / desfases silenciosos
# Si no hay info de que perteneciera al índice (NaN): no pertenecía al índice
in_sp500_monthly = in_sp500_monthly.reindex(log_rets.index).fillna(0.0)

# Universo: activos que han estado en el índice en TODOS los 13 meses anteriores al mes de rebalanceo (t-13 a t-1)
# Rolling ventana 13 meses; shift(1) para que en la fecha t la elegibilidad dependa solo de t-13..t-1 (sin incluir t), evitando look-ahead.
window = 13
membership_13m = (
    in_sp500_monthly
    .rolling(window=window, min_periods=window)
    .sum()
)

# Un activo pertenece al universo en t si ha estado en el S&P 500 en los 13 meses anteriores al actual (t-13 a t-1)
universe_mask = (membership_13m.shift(1) == window)

print('> Universo 13 meses calculado')
print(f"  - Shape universe_mask: {universe_mask.shape}")

> Universo 13 meses calculado
  - Shape universe_mask: (146, 1234)

## <font color=#0099CC>**3. MOMENTUM 12 Y 6 MESES (CON LAG)**</font>

### <font color=#336699>**3.1. Cálculo de R_12 y R_6**</font>

Con retornos logarítmicos mensuales:

$$
r_t = \ln\left(\frac{P_t}{P_{t-1}}\right)
$$

se definen:

- **R_12 (momentum 12 meses)**: rentabilidad desde el mes \(t-13\) al mes \(t-1\),

$$
R_{12,t} = \sum_{k=1}^{12} r_{t-k}
$$

- **R_6 (momentum 6 meses)**: rentabilidad desde el mes \(t-7\) al mes \(t-1\),

$$
R_{6,t} = \sum_{k=1}^{6} r_{t-k}
$$

El **lag de 1 mes** se implementa con `.shift(1)`: para el rebalanceo en la fecha \(t\) solo se usan retornos hasta \(t-1\), evitando *look-ahead bias* (no se utiliza el mes actual).

In [13]:
# Cálculo de momentum 12 y 6 meses con lag de 1 mes

# log_rets.index son fines de mes. r_t = log(P_t / P_{t-1}).
# Para el rebalanceo en el mes t usamos retornos hasta t-1.

mom_12 = (
    log_rets
    .rolling(window=12, min_periods=12)
    .sum()
    .shift(1)
)

mom_6 = (
    log_rets
    .rolling(window=6, min_periods=6)
    .sum()
    .shift(1)
)

# Filtrar al periodo de backtest
mask_dates = (log_rets.index >= BACKTEST_START) & (log_rets.index <= BACKTEST_END)

mom_12 = mom_12.loc[mask_dates]
mom_6 = mom_6.loc[mask_dates]
universe_mask_bt = universe_mask.loc[mask_dates]

print('> Momentum 12 y 6 meses calculado (con lag)')
print(f"\nmom_12: {mom_12.shape}")
display(mom_12.head())
print(f"\nmom_6: {mom_6.shape}")
display(mom_6.head())

> Momentum 12 y 6 meses calculado (con lag)

mom_12: (132, 1234)

symbol,A,AABA-201910,AAL,AAMRQ-201312,AAP,AAPL,AAV-199901,ABBV,ABI-200811,ABKFQ-201304,ABMD-202212,ABNB,ABS-200606,ABT,ACAS-201701,ACGL,ACKH-200712,ACN,ACS-201002,ACV-201105,ACY-199411,ADBE,ADCT-201012,ADI,ADM,ADP,ADSK,ADT-201604,AEE,AEP,AES,AET-201811,AFL,AFS-200011,AGC-200108,AGN-201503,AHM-199810,AIG,AIT-199910,AIV,AIZ,AJG,AKAM,AKS-202003,AL-200711,ALB,ALGN,ALK,ALL,ALLE,ALTR-201512,ALXN-202107,AM-201308,AMAT,AMCC-201701,AMCR,AMD,AME,AMG,AMGN,AMH-199709,AMP,AMT,AMTM,AMX-199311,AMZN,AN-199812,ANDV-201809,ANDW-200712,ANET,ANF,ANRZQ-201607,ANSS-202507,ANV-199904,AON,AOS,APA,APC-201908,APCC-200702,APD,APH,APO,APOL-201702,APP,APTV,AR-199911,ARC-200004,ARE,ARES,ARG-201605,AS-199909,ASC-199906,ASH,ASN-200710,ASND-199906,ASO-200611,AT-200711,ATGE,ATI-199906,ATO,ATVI-202310,AV-200710,AVB,AVGO,AVP-202001,AVY,AW-200812,AWE-200410,AWK,AXON,AXP,AYE-201102,AYI,AZA-200106,AZO,B,BA,BAC,BALL,BAX,BAY-199808,BBBYQ-202309,BBI-199801,BBWI,BBY,BC,BCO,BCR-201712,BDK-201003,BDX,BEAM-201404,BEN,BEV-200603,BF.B,BFH,BFI-199907,BFO-200010,BG,BGEN-200311,BGGSQ-202101,BHF,BHMSQ-200401,BIGGQ,BIO,BJS-201004,BK,BKB-199909,BKNG,BKR,BLDR,BLK,BLS-200612,BLY-199612,BMC-201309,BMET-200709,BMG-200101,BMS-201906,BMY,BN-199503,BNI-201002,BNL-199806,BNSSA-201206,BOAT-199701,BOL-200710,BR-200603,BRCM-201601,BRK.B,BRL-200812,BRNO-199508,BRO,BSC-200805,BSET,BSX,BT-199906,BTUUQ-201704,BUD-200811,BV-199409,BVSN-202005,BWA,BWY-199510,BX,BXLT-201606,BXP,C,CA-201811,CAG,CAH,CAL,CAM-201604,CAR,CARR,CAT,CB-201601,CBB-199801,CBE-201211,CBH-200803,CBL-199010,CBOE,CBRE,CBS-200005,CBSS-200709,CCB-199602,CCEP,CCI,CCK,CCL,CCTYQ-201109,CCU-200807,CDNS,CDW,CE-200402,CEG,CELG-201911,CEN-200711,CEPH-201110,CERN-202206,CF,CFC-200806,CFG,CFL-199804,CFN-201503,CG-200011,CGP-200101,CHA-200006,CHD,CHIR-200604,CHKAQ-202102,CHRS-201206,CHRW,CHTR,CI,CIC-199505,CIEN,CIN-200603,CINF,CITGQ-200912,CKL-199505,CL,CLF,CLX,CMA,CMB-199603,CMCSA,CMCSK-201512,CME,CMG,CMI,CMS,CMVT-201302,CMX-200703,CNA,CNC,CNCEQ-200309,CNG-200001,CNP,CNW-201510,CNX,CNXT-201104,COC-200208,COF,COIN,COL-201811,COMS-201004,COO,COP,COR,COST,COTY,COV-201501,CPAY,CPB,CPGX-201606,CPNLQ-200802,CPPRQ-202102,CPQ-200205,CPRI,CPRT,CPT,CPWR-201412,CRH,CRL,CRM,CRR-199706,CRWD,CSCO,CSE-199911,CSGP,CSR-200006,CSRA-201804,CSX,CTAS,CTB-202106,CTCO-199110,CTLT-202412,CTRA,CTSH,CTVA,CTX-200908,CTXS-202209,CUE-199309,CVC-201606,CVG-201810,CVGQE-200412,CVH-201305,CVN-199112,CVNA,CVS,CVX,CXO-202101,CXT,CYM-199912,CYR-199606,CZR,D,DAL,DASH,DAY,DCNAQ-200801,DD,DDOG,DDS,DE,DEC-199806,DECK,DELL-201310,DFODQ-202106,DFS-202505,DG,DGN-199910,DGX,DHI,DHR,DI-199809,DIGI-199809,DINO,DIS,DISCK-202204,DISH-202312,DJ-200712,DLR,DLTR,DLX,DNB-201902,DNRCQ-202009,DOC,DOFSQ-202104,DOV,DOW-201708,DPHIQ-200910,DPZ,DRE-202209,DRI,DTE,DTV-201507,DUK,DVA,DVN,DWD-199705,DXC,DXCM,DYHGQ-200012,DYN-201804,E-199504,EA,EBAY,EC-200606,ECH-199807,ECL,ECO-200301,ED,EDS-200808,EFU-200011,EFX,EG,EHC,EIX,EKDKQ-201309,EL,ELV,EMC-201609,EME,EMN,EMR,ENDPQ-202405,ENPH,ENRNQ-200411,ENS-199708,EOG,EOP-200702,EP-201205,EPAM,EQ-200906,EQIX,EQR,EQT,ERIE,ES,ESRX-201812,ESS,ESY-199505,ETFC-202010,ETN,ETR,ETS-200603,ETSY,EVHC-201810,EVRG,EW,EXC,EXE,EXPD,EXPE,EXR,F,FANG,FAST,FBF-200403,FBIN,FBO-199603,FCN-199810,FCX,FDC-200709,FDO-201507,FDS,FDX,FE,FFB-199512,FFIV,FG-199804,FHI,FHN,FICO,FIS,FISV,FITB,FIX,FJ-200011,FJCC-200809,FL-202509,FLIR-202105,FLMIQ-200408,FLR,FLS,FLTWQ-200907,FMC,FMCC,FMY-199905,FNB-199511,FNMA,FOSL,FOXA,FPC-200011,FRCB,FRM-199612,FRO-199909,FRT,FRX-201406,FSH-200611,FSL.B-200612,FSLR,FTI,FTL-200004,FTNT,FTRCQ-202104,FTV,FWLT-201412,G-200509,GAP,GAPTQ-201203,GAS-201606,GBLXQ-200312,GCO,GD,GDDY,GDT-200604,GDW-200609,GE,GEB-199408,GEHC,GEN,GENZ-201104,GEV,GFS.A-199810,GGP-201808,GHC-199308,GIC-200001,GIDL-199709,GILD,GIS,GL,GLD-199705,GLK-200507,GLW,GM,GMCR-201603,GME,GNE-199906,GNN-199006,GNRC,GNT-199806,GNW,GOOGL,GOSHA-200507,GP-200512,GPC,GPN,GPU-200111,GQ-199404,GR-201207,GRA-202109,GRMN,GRN-199812,GS,GSX-199810,GT,GTE-200006,GTW-200710,GWF-199707,GWOW-201009,GWW,H-200704,HAL,HAR-201703,HAS,HBAN,HBI-202511,HBJ-199111,HBOC-199901,HCA,HCBK-201510,HCR-200712,HD,HDLM-201301,HES-202507,HET-200801,HFS-199712,HI-200303,HIA-199002,HIG,HII,HLT,HM-200112,HMA-201401,HNZ-201306,HOG,HOLX,HON,HOOD,HOT-201609,HP,HPC-200811,HPE,HPQ,HRB,HRL,HRZIQ-200107,HSH-201408,HSIC,HSP-201509,HST,HSY,HTMXQ-201305,HUBB,HUM,HWM,I-199603,IAC,IBKR,IBM,ICE,IDXX,IEX,IFF,IGT-201504,IK-199902,IKN-200810,ILMN,IMNX-200207,INCLF-200701,INCY,INFO-202202,INGR-200611,INTC,INTU,INVH,IP,IPG-202511,IPGP,IQV,IR,IRM,ISRG,ISS-199206,IT,ITT,ITW,IVZ,J,JAVA-201001,JBHT,JBL,JCI,JEF,JH-200705,JHF-200404,JKHY,JNJ,JNPR-202507,JNS-201705,JNY-201404,JOS-200005,JOY-201704,JP-200603,JPM,JWN-202505,JWP-199310,K-202512,KATE-201707,KBH,KDP,KEY,KEYS,KG-201102,KHC,KIM,KKR,KLAC,KM-200212,KMB,KMG-200608,KMI,KMX,KO,KR,KRB-200512,KRFT-201507,KRI-200606,KSE-200708,KSS,KSU-202112,KVUE,KWP-199911,L,LCE-199404,LDG-200810,LDOS,LDW-200012,LEG,LEHMQ-201203,LEN,LH,LHX,LIFE-201402,LII,LIN,LINB-199510,LIT-200105,LKQ,LLL-201906,LLTC-201703,LLX-199710,LLY,LM-202007,LMT,LNC,LNT,LO-201506,LOR-199604,LOTS-199507,LOW,LPX,LRCX,LSI-201405,LU-200611,LUB-202205,LULU,LUMN,LUV,LVLT-201710,LVS,LW,LXK-201611,LYB,LYV,M,MA,MAA,MAC,MAI-199506,MAR,MAS,MAT,MAY-200508,MBI,MCA-199101,MCAWA-199409,MCD,MCHP,MCIC-199809,MCK,MCO,MD-199707,MDLZ,MDP-202112,MDRIQ-202006,MDT,MEA-200201,MEDI-200706,MEE-201106,MEL-200706,MER-200812,MERQ-200611,MET,META,MFE-201102,MGM,MHC-199112,MHK,MHS-201203,MI-201107,MII-199906,MIL-201007,MIR-201012,MJN-201706,MKC,MKG-200010,MKTX,ML-199503,MLM,MMI-201205,MMM,MNKKQ-202206,MNST,MO,MOB-199911,MOH,MOLX-201312,MON-201806,MOS,MPC,MPWR,MRK,MRN-199606,MRNA,MRO-202411,MRSH,MS,MSCI,MSFT,MSI,MST-199808,MTB,MTCH,MTD,MTG,MTL-199909,MTLQQ-201103,MTW,MU,MUR,MWI-200402,MWV-201507,MWW-201610,MXIM-202108,MXS-199506,MYG-200603,MZIAQ-201302,NAE-199708,NAV-202106,NAVI,NBL-202010,NBR,NC,NCC-200812,NCE-200008,NCLH,NCR-199109,NDAQ,NDSN,NEBLQ-202102,NEC-199706,NEE,NEM,NEU,NFB-200611,NFLX,NFX-201902,NGH-200012,NI,NKE,NKTR,NL,NLC-199912,NLSN-202210,NMK-200201,NOC,NOV,NOVL-201104,NOW,NRG,NRT-199008,NRTLQ-201510,NSC,NSI-200306,NSM-201109,NTAP,NTRS,NUE,NVDA,NVLS-201206,NVR,NWL,NWSA,NXPI,NXTL-200508,NYN-199708,NYT,NYX-201311,O,OAT-200108,ODFL,ODP-202512,OGN,OI,OK-200103,OKE,OM-199709,OMC,OMX-201311,ON,ONE-200406,ORCL,ORLY,ORX-199902,OTIS,OWENQ-200610,OXY,PAC-199703,PALM-201006,PANW,PAS-201002,PAYC,PAYX,PBCT-202204,PBG-201002,PBI,PBY-201602,PCAR,PCG,PCH,PCI-199407,PCL-201602,PCLB-199310,PCP-201601,PCS-200404,PD-200703,PDCO-202504,PDG-200603,PDQ-199207,PEG,PEL-199706,PENN,PEP,PET-199806,PETM-201503,PFE,PFG,PG,PGL-200702,PGN-201207,PGR,PH,PHA-200304,PHB-199910,PHL-199008,PHM,PIN-199410,PKG,PLD-201106,PLL-201508,PLTR,PM,PMCS-201601,PMI-199911,PN-199109,PNC,PNR,PNU-200003,PNW,PODD,POM-201603,POOL,PPG,PPL,PPW-199911,PRD-200110,PRGO,PRSU,PRU,PSA,PSFT-200501,PSKY,PSX,PT-199505,PTC,PTV-201011,PVH,PVN-200509,PVT-199906,PWER-201307,PWJ-200011,PWR,PX-201810,PXD-202405,PYPL,PZE-199908,Q-201103,QCOM,QEP-202103,QLGC-201608,QRVO,QTRN-200309,R,RADCQ-202409,RAI-201707,RAL-200112,RATL-200302,RBD-199903,RBK-200601,RCL,RDC-201904,REG,REGN,RF,RHI,RHT-201907,RIG,RJF,RL,RLM-200005,RMD,RML-200608,RNB-199912,ROH-200904,ROK,ROL,ROP,ROST,RRC,RRD-202202,RSG,RSHCQ-201510,RTN-202004,RTX,RVTY,RX-201002,RYAN-200610,RYC-199908,RYI-200710,S-202003,SAF-200809,SAI-199812,SANM,SAPE-201502,SB-199711,SBAC,SBL-200701,SBNY,SBUX,SCG-201812,SCHW,SCI,SDH-200106,SDS-200508,SE-201702,SEBL-200601,SEDG,SEE,SEG-200011,SFA-200602,SFS-200008,SFX-199509,SGID-200610,SGP-200911,SHEL,SHLDQ-202210,SHOY-200204,SHW,SIAL-201511,SIG,SII-201008,SITC,SIVBQ-202411,SJM,SK-199805,SKY,SLB,SLG,SLM,SLR-200710,SMCI,SMI-200109,SMS-200007,SNA,SNC-199511,SNDK,SNI-201803,SNPS,SNT-199910,SNV-202512,SO,SOLS,SOLV,SOTR-200410,SOV-200901,SPC-199204,SPG,SPGI,SPLS-201709,SPP-199512,SPXC,SQD-199105,SRCL-202411,SRE,SRR-200708,SSP,STE,STI-201912,STJ-201701,STLD,STO-199811,STR-201609,STT,STX,STZ,SUB-200102,SUN-201210,SUNEQ-201712,SVU-201810,SW,SWK,SWKS,SWN-202409,SWY-201501,SXCL-201702,SYF,SYK,SYN-199410,SYY,T,TA-199907,TAP,TAP.B-200404,TCOMA-199903,TDC,TDG,TDM-199708,TDY,TE-201606,TECH,TEG-201506,TEK-200711,TEL,TEN-202211,TER,TEX,TFC,TFCFA-201903,TFX,TGNA,TGT,THC,THY-199708,TIC-199312,TIE-201301,TIF-202101,TIN-201202,TJX,TKA-199108,TKO,TKR,TLAB-201312,TMC-200006,TMO,TMUS,TNB-201205,TNL,TOS-200109,TOY-200507,TPL,TPR,TRB-200712,TRGP,TRIP,TRMB,TROW,TRV,TRW-200212,TSCO,TSG-200703,TSLA,TSN,TSS-201909,TT,TTD,TTWO,TUPBQ-202506,TWC-201605,TWTR-202210,TWX-201806,TX-200110,TXN,TXT,TXU-200710,TYL,UAA,UAL,UALAQ-200602,UAWGQ-200303,UBER,UCC-199904,UCL-200508,UCM-200010,UDR,UH-200005,UHS,UIS,UK-200102,ULTA,UMG-200006,UN-202011,UNH,UNM,UNP,UPC-200406,UPR-200007,UPS,URBN,URI,USB,USBC-199708,USG-201904,USH-199706,USHC-199607,USS-199810,UST-200901,USW-200006,UVN-200703,V,VALPQ-202104,VAR-202104,VAT-199609,VFC,VIAB-201912,VIAV,VICI,VLO,VLTO,VMC,VNO,VNT,VO-200012,VRSK,VRSN,VRTS-200507,VRTX,VST,VSTNQ-201010,VTR,VTRS,VTSS-201504,VYX,VZ,WAB,WAI-199808,WAMUQ-201203,WAN.B-199309,WAT,WB-200812,WBA-202508,WBD,WCG-202001,WCOEQ-200404,WDAY,WDC,WEC,WELL,WEN-200809,WETT-199210,WFC,WFM-201708,WFRD,WHR,WINMQ-202009,WLA-200006,WLBAQ-202004,WLL-200203,WLP-200411,WM,WMB,WMT,WNDXQ-200611,WOR,WPX-202101,WRB,WRK-202407,WSM,WST,WTW,WU,WWY-200810,WY,WYE-200910,WYNN,X-202506,XEC-202109,XEL,XL-201809,XLNX-202202,XOM,XRAY,XRX,XTO-201006,XYL,XYZ,YELLQ,YNR-200010,YUM,ZBH,ZBRA,ZE-199805,ZION,ZRN-199806,ZTS
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2015-01-31,0.008106,0.222352,0.758321,NaN,0.365797,0.340910,NaN,0.246221,NaN,NaN,0.353003,NaN,NaN,0.183019,-0.068125,-0.009933,NaN,0.108147,NaN,NaN,NaN,0.193999,NaN,0.114665,0.201533,0.186033,0.176942,-0.086785,0.283296,0.300456,-0.038160,0.270522,-0.064597,NaN,NaN,0.650388,NaN,0.102005,NaN,0.392340,0.046659,0.034114,0.288530,-0.322425,NaN,-0.035846,-0.021761,0.498699,0.271808,0.233075,0.147651,0.331041,NaN,0.362526,-0.718214,NaN,-0.371176,0.005516,-0.021626,0.353001,NaN,0.158918,0.229235,NaN,NaN,-0.250734,NaN,0.257697,NaN,NaN,-0.117286,-1.452889,-0.061485,NaN,0.133682,0.057183,-0.304493,0.049944,NaN,0.278328,0.196972,-0.173954,0.221971,NaN,0.204977,NaN,NaN,0.370059,NaN,0.048703,NaN,NaN,0.223574,NaN,NaN,NaN,NaN,0.298373,NaN,0.235100,0.131891,NaN,0.355838,0.658662,-0.588113,0.060279,NaN,NaN,0.258002,0.511329,0.035972,NaN,0.252094,NaN,0.258798,-0.482454,-0.025795,0.146135,0.285881,0.080660,NaN,-0.052802,NaN,0.376178,0.000752,0.117199,-0.320066,0.224415,NaN,0.248993,NaN,-0.023762,NaN,0.163498,0.084279,NaN,NaN,0.117639,NaN,-0.039797,NaN,NaN,0.226265,-0.024984,NaN,0.168068,NaN,-0.019275,0.025028,-0.037147,0.145799,NaN,NaN,NaN,NaN,NaN,0.125958,0.132605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.393273,0.236216,NaN,NaN,0.060590,NaN,0.273287,0.097426,NaN,-0.902311,NaN,NaN,-0.472906,-0.008577,NaN,0.130388,NaN,0.304400,0.038469,-0.066535,0.104907,0.207382,0.142919,-0.175458,0.495318,NaN,0.034175,0.089952,NaN,NaN,NaN,NaN,0.213648,0.264118,NaN,NaN,NaN,0.023922,0.094137,0.132802,0.146125,NaN,NaN,0.302374,0.415719,NaN,NaN,0.280674,NaN,NaN,0.148445,0.176687,NaN,NaN,NaN,0.398914,NaN,NaN,NaN,0.191481,NaN,-0.256629,NaN,0.272607,0.197488,0.162951,NaN,-0.209344,NaN,0.025907,NaN,NaN,0.080669,-1.261913,0.147785,0.001268,NaN,0.122917,0.156330,0.168345,0.250595,0.041886,0.297099,NaN,NaN,-0.053642,0.566258,NaN,NaN,0.050224,0.225008,-0.111600,NaN,NaN,0.090488,NaN,0.148987,NaN,0.269590,0.014997,0.262011,0.186151,0.315371,0.42704,0.238372,0.044931,NaN,NaN,-0.345033,NaN,-0.077972,-0.004375,0.299135,-0.015056,-0.028685,0.182196,0.071996,NaN,NaN,0.246492,NaN,-0.005160,NaN,NaN,0.250946,0.298937,0.380250,NaN,NaN,-0.266987,0.042081,NaN,NaN,0.008658,NaN,0.174329,-0.019579,NaN,NaN,NaN,NaN,0.311624,-0.072451,-0.079464,-0.117386,NaN,NaN,-0.242220,0.206962,0.590748,NaN,NaN,NaN,NaN,NaN,0.255099,-0.005476,NaN,0.075021,NaN,0.137383,0.173291,0.158782,NaN,0.247276,0.133777,0.109619,NaN,NaN,-0.212425,0.221961,-0.217910,0.229889,NaN,0.354689,0.221085,0.197323,0.001401,-0.685740,0.245312,-0.361324,-0.092025,0.057525,NaN,0.314182,0.333295,0.119952,0.298622,0.227478,0.233874,0.178316,0.003553,NaN,0.134924,0.441248,NaN,0.343814,NaN,0.717584,0.022617,NaN,NaN,0.013002,NaN,0.221543,NaN,NaN,0.171029,0.108324,0.164806,0.384697,NaN,0.023130,0.323617,0.187408,0.054490,-0.044413,-0.101142,0.066797,0.812681,NaN,NaN,0.098150,NaN,NaN,0.312347,NaN,0.283566,0.357379,-0.169349,0.250749,0.267095,0.186843,0.392127,NaN,0.211054,-0.085796,0.369953,NaN,NaN,0.175511,0.286812,0.661163,0.340278,NaN,0.022157,0.211413,0.364465,0.036301,0.122608,0.023124,NaN,0.001568,NaN,NaN,-0.443356,NaN,0.211663,0.272346,0.193838,0.211421,NaN,0.361785,NaN,0.169155,0.169348,0.141577,0.164253,0.183873,-0.007633,-0.109823,NaN,NaN,0.322719,0.083134,NaN,-0.269408,-0.266670,NaN,-0.270748,-0.342005,NaN,NaN,-0.381664,-0.079806,NaN,NaN,0.006717,NaN,NaN,0.301708,NaN,NaN,NaN,-0.203145,NaN,NaN,0.471701,0.428691,NaN,-0.169878,NaN,0.095584,NaN,0.182355,NaN,0.047577,0.387029,NaN,NaN,NaN,-0.068963,NaN,NaN,0.110845,NaN,NaN,NaN,0.363609,NaN,NaN,NaN,0.227237,0.097777,0.048458,NaN,NaN,0.271650,-0.122884,0.570455,-0.344062,NaN,NaN,-0.191687,NaN,-0.602708,-0.055418,NaN,NaN,0.273157,0.217999,NaN,NaN,NaN,-0.035832,0.168434,NaN,0.102424,NaN,0.189468,NaN,NaN,NaN,NaN,0.015118,NaN,-0.243265,0.277226,0.031235,0.107755,0.476397,NaN,NaN,0.430647,0.087392,NaN,0.264188,NaN,-0.105173,NaN,NaN,NaN,NaN,0.158085,0.232202,0.159210,NaN,NaN,NaN,-0.032821,0.179334,0.109283,NaN,0.069687,-0.193059,NaN,NaN,0.378485,0.173046,0.159367,NaN,NaN,0.175281,0.394586,0.235259,0.087606,NaN,-0.001503,0.339012,0.404215,NaN,-0.103802,0.197282,-0.132242,-0.012472,0.332111,0.067506,0.181806,-0.024100,NaN,NaN,0.512254,NaN,NaN,0.367421,NaN,NaN,0.366390,0.199307,NaN,0.132546,0.179967,-0.035276,0.239326,NaN,0.321187,0.320024,NaN,0.169930,-0.060600,0.139652,0.108283,-0.343226,NaN,0.096501,0.241004,0.082955,-0.224329,NaN,NaN,0.063303,0.159883,-0.002310,0.291223,NaN,NaN,-0.215183,NaN,0.094244,0.269795,NaN,0.098595,-0.001872,-0.093465,0.413288,0.053835,NaN,NaN,NaN,0.281115,0.039666,0.332597,NaN,0.173527,NaN,0.208544,0.347831,0.051321,0.499575,NaN,0.186734,NaN,NaN,0.100538,-0.004358,NaN,NaN,-0.132240,NaN,NaN,-0.032795,NaN,0.354568,NaN,0.128761,0.166288,0.052870,NaN,0.124322,NaN,NaN,NaN,-0.156992,0.187638,0.031483,NaN,0.334711,0.217240,0.290886,0.123412,0.288171,0.259690,NaN,NaN,0.345030,-0.111321,0.383874,NaN,NaN,-0.528687,-0.056451,0.275114,0.816718,0.397900,-0.274678,NaN,0.181199,0.017477,0.278659,0.228029,0.036577,0.250058,0.386775,NaN,0.470254,0.116058,-0.386791,NaN,-0.224401,NaN,NaN,-0.001015,0.039276,NaN,0.256671,0.212495,NaN,0.044816,0.084097,-1.146693,0.248003,NaN,NaN,NaN,NaN,NaN,NaN,0.029322,0.356034,NaN,-0.095395,NaN,0.042470,NaN,NaN,NaN,NaN,NaN,0.198812,0.096291,NaN,0.079893,NaN,0.111578,NaN,0.182352,0.639192,0.469247,0.296261,NaN,0.432063,NaN,0.040320,-0.013872,0.004548,0.371180,0.156422,NaN,NaN,-0.198426,0.190082,0.223766,0.085704,0.243453,0.013987,NaN,0.099106,NaN,0.220576,0.099180,NaN,NaN,-0.049993,0.476020,-0.227111,NaN,0.238020,-0.433917,0.167825,NaN,NaN,NaN,NaN,-0.131625,NaN,-0.351225,-0.258701,-0.028451,NaN,NaN,0.276341,NaN,0.200576,0.058769,-0.623362,NaN,0.246242,-0.188050,0.200787,NaN,-0.074875,0.096306,NaN,0.281973,0.213132,0.311622,-0.262364,NaN,-0.004692,NaN,0.272993,-0.067826,NaN,0.191769,-0.045622,NaN,-0.839101,0.188555,NaN,NaN,0.023983,0.105354,-0.055552,0.242129,NaN,0.217527,0.181880,-0.138459,0.508864,NaN,NaN,-0.171678,NaN,0.295316,NaN,0.381414,0.483033,NaN,-0.281923,NaN,-0.054750,NaN,0.066835,NaN,0.206501,NaN,0.173741,0.403158,NaN,NaN,NaN,-0.050497,NaN,NaN,0.757419,NaN,NaN,0.048426,0.049359,NaN,0.073888,-0.212085,0.167935,0.317473,0.038076,NaN,-0.041495,NaN,-0.111045,NaN,NaN,0.173380,NaN,NaN,0.295538,NaN,-0.042772,0.159273,NaN,0.122585,0.051420,0.077316,0.143437,NaN,NaN,0.051765,0.019628,NaN,NaN,NaN,0.063617,NaN,0.232017,NaN,0.184085,NaN,-0.021402,0.353872,NaN,NaN,0.184834,-0.141132,NaN,0.296644,0.216328,0.384961,0.101758,0.211129,0.232375,NaN,NaN,0.088315,0.036743,0.006404,0.237732,NaN,-0.132222,-0.048802,NaN,0.034984,NaN,-0.058212,NaN,NaN,NaN,NaN,-0.105853,0.016228,-0.211949,NaN,NaN,NaN,0.022316,-0.413295,0.118628,NaN,NaN,0.247028,0.396200,0.296556,NaN,NaN,NaN,NaN,0.570673,-0.405328,0.354426,0.399123,0.082754,0.344894,0.210068,-0.915642,0.105455,0.058391,NaN,0.195837,NaN,NaN,NaN,-0.039815,0.106130,0.125651,0.240053,-0.453545,-0.128011,0.221253,-1.949764,0.200857,0.031812,0.065344,NaN,NaN,NaN,NaN,-0.951797,NaN,NaN,0.342867,0.359895,NaN,0.209336,NaN,0.159218,0.060563,0.292438,0.158519,0.241108,NaN,NaN,0.054402,NaN,NaN,0.238364,NaN,NaN,NaN,NaN,NaN,NaN,-0.012730,-0.113986,NaN,0.370547,0.387252,0.520843,NaN,0.214027,0.101567,-0.001439,NaN,-0.241603,-0.036972,0.272943,0.088004,NaN,0.709333,NaN,NaN,0.237308,NaN,NaN,-0.127891,0.069042,NaN,0.084911,0.225109,NaN,NaN,NaN,NaN,NaN,0.271723,0.143752,0.168899,NaN,-0.132538,NaN,0.120753,0.241334,NaN,0.028593,0.316355,0.147655,0.065004,0.034069,NaN,0.126996,0.083364,0.202537,0.332792,NaN,NaN,0.402139,0.285622,-0.078618,0.197556,0.941386,-0.365467,0.211038,-0.148014,NaN,0.242235,NaN,0.125717,0.006573,NaN,0.305161,NaN,NaN,-0.040602,0.335391,NaN,0.111936,0.222373,-0.010589,0.401671,NaN,0.156273,0.000707,0.125498,-0.403892,0.066648,0.095151,0.214341,0.102166,0.213725,0.184811,NaN,NaN,NaN,0.156245,NaN,0.084680,NaN,-0.261982,0.099127,NaN,NaN,0.122781,-0.222104,NaN,0.169885,NaN,NaN,0.167583,-0.367580,NaN,0.208255,-0.103846,-0.268087,0.045999,0.179080,NaN,0.025101,NaN,0.391031,0.188947,0.033089,0.044983,NaN,0.478531,-0.369046,0.136305,-0.573498,0.262900,NaN,0.223789,0.137888,NaN,0.069130,0.441833,0.569947,NaN,NaN,NaN,NaN,NaN,NaN,0.316310,NaN,0.317227,-0.129921,NaN,0.281029,NaN,0.008220,0.310833,0.012556,0.367778,NaN,NaN,0.083136,-0.054561,0.269003,0.129000,NaN,-0.013837,NaN,NaN,NaN,NaN,NaN,NaN,0.170888,-0.580025,0.107534,NaN,0.200419,-0.133150,0.055060,NaN,0.002486,NaN,0.104373,0.310311,NaN,NaN,-0.025739,-0.047620,NaN,0.469330,NaN,NaN,0.269339,0.261478,0.258140,-0.156012,-0.005491,0.159418,NaN,NaN,NaN,0.119737,NaN,0.302583,-0.293259,0.152973,NaN,-0.018815,0.292630,0.278006,0.395684,NaN,NaN,0.215982,-0.126285,-0.302205,0.229774,0.139004,NaN,0.586826,NaN,NaN,0.167533,0.193485,0.112175,NaN,-0.318632,-0.560966,0.195696,NaN,0.282095,0.090978,0.027952,0.067098,NaN,0.159958,NaN,-0.234300,-0.091473,0.015451,0.288871,0.095842,-0.033594,-0.062471,0.099735,0.149865,NaN,0.109459,NaN,0.258326,NaN,-0.016690,0.205032,0.358652,NaN,-0.044107,NaN,0.283659

mom_6: (132, 1234)

symbol,A,AABA-201910,AAL,AAMRQ-201312,AAP,AAPL,AAV-199901,ABBV,ABI-200811,ABKFQ-201304,ABMD-202212,ABNB,ABS-200606,ABT,ACAS-201701,ACGL,ACKH-200712,ACN,ACS-201002,ACV-201105,ACY-199411,ADBE,ADCT-201012,ADI,ADM,ADP,ADSK,ADT-201604,AEE,AEP,AES,AET-201811,AFL,AFS-200011,AGC-200108,AGN-201503,AHM-199810,AIG,AIT-199910,AIV,AIZ,AJG,AKAM,AKS-202003,AL-200711,ALB,ALGN,ALK,ALL,ALLE,ALTR-201512,ALXN-202107,AM-201308,AMAT,AMCC-201701,AMCR,AMD,AME,AMG,AMGN,AMH-199709,AMP,AMT,AMTM,AMX-199311,AMZN,AN-199812,ANDV-201809,ANDW-200712,ANET,ANF,ANRZQ-201607,ANSS-202507,ANV-199904,AON,AOS,APA,APC-201908,APCC-200702,APD,APH,APO,APOL-201702,APP,APTV,AR-199911,ARC-200004,ARE,ARES,ARG-201605,AS-199909,ASC-199906,ASH,ASN-200710,ASND-199906,ASO-200611,AT-200711,ATGE,ATI-199906,ATO,ATVI-202310,AV-200710,AVB,AVGO,AVP-202001,AVY,AW-200812,AWE-200410,AWK,AXON,AXP,AYE-201102,AYI,AZA-200106,AZO,B,BA,BAC,BALL,BAX,BAY-199808,BBBYQ-202309,BBI-199801,BBWI,BBY,BC,BCO,BCR-201712,BDK-201003,BDX,BEAM-201404,BEN,BEV-200603,BF.B,BFH,BFI-199907,BFO-200010,BG,BGEN-200311,BGGSQ-202101,BHF,BHMSQ-200401,BIGGQ,BIO,BJS-201004,BK,BKB-199909,BKNG,BKR,BLDR,BLK,BLS-200612,BLY-199612,BMC-201309,BMET-200709,BMG-200101,BMS-201906,BMY,BN-199503,BNI-201002,BNL-199806,BNSSA-201206,BOAT-199701,BOL-200710,BR-200603,BRCM-201601,BRK.B,BRL-200812,BRNO-199508,BRO,BSC-200805,BSET,BSX,BT-199906,BTUUQ-201704,BUD-200811,BV-199409,BVSN-202005,BWA,BWY-199510,BX,BXLT-201606,BXP,C,CA-201811,CAG,CAH,CAL,CAM-201604,CAR,CARR,CAT,CB-201601,CBB-199801,CBE-201211,CBH-200803,CBL-199010,CBOE,CBRE,CBS-200005,CBSS-200709,CCB-199602,CCEP,CCI,CCK,CCL,CCTYQ-201109,CCU-200807,CDNS,CDW,CE-200402,CEG,CELG-201911,CEN-200711,CEPH-201110,CERN-202206,CF,CFC-200806,CFG,CFL-199804,CFN-201503,CG-200011,CGP-200101,CHA-200006,CHD,CHIR-200604,CHKAQ-202102,CHRS-201206,CHRW,CHTR,CI,CIC-199505,CIEN,CIN-200603,CINF,CITGQ-200912,CKL-199505,CL,CLF,CLX,CMA,CMB-199603,CMCSA,CMCSK-201512,CME,CMG,CMI,CMS,CMVT-201302,CMX-200703,CNA,CNC,CNCEQ-200309,CNG-200001,CNP,CNW-201510,CNX,CNXT-201104,COC-200208,COF,COIN,COL-201811,COMS-201004,COO,COP,COR,COST,COTY,COV-201501,CPAY,CPB,CPGX-201606,CPNLQ-200802,CPPRQ-202102,CPQ-200205,CPRI,CPRT,CPT,CPWR-201412,CRH,CRL,CRM,CRR-199706,CRWD,CSCO,CSE-199911,CSGP,CSR-200006,CSRA-201804,CSX,CTAS,CTB-202106,CTCO-199110,CTLT-202412,CTRA,CTSH,CTVA,CTX-200908,CTXS-202209,CUE-199309,CVC-201606,CVG-201810,CVGQE-200412,CVH-201305,CVN-199112,CVNA,CVS,CVX,CXO-202101,CXT,CYM-199912,CYR-199606,CZR,D,DAL,DASH,DAY,DCNAQ-200801,DD,DDOG,DDS,DE,DEC-199806,DECK,DELL-201310,DFODQ-202106,DFS-202505,DG,DGN-199910,DGX,DHI,DHR,DI-199809,DIGI-199809,DINO,DIS,DISCK-202204,DISH-202312,DJ-200712,DLR,DLTR,DLX,DNB-201902,DNRCQ-202009,DOC,DOFSQ-202104,DOV,DOW-201708,DPHIQ-200910,DPZ,DRE-202209,DRI,DTE,DTV-201507,DUK,DVA,DVN,DWD-199705,DXC,DXCM,DYHGQ-200012,DYN-201804,E-199504,EA,EBAY,EC-200606,ECH-199807,ECL,ECO-200301,ED,EDS-200808,EFU-200011,EFX,EG,EHC,EIX,EKDKQ-201309,EL,ELV,EMC-201609,EME,EMN,EMR,ENDPQ-202405,ENPH,ENRNQ-200411,ENS-199708,EOG,EOP-200702,EP-201205,EPAM,EQ-200906,EQIX,EQR,EQT,ERIE,ES,ESRX-201812,ESS,ESY-199505,ETFC-202010,ETN,ETR,ETS-200603,ETSY,EVHC-201810,EVRG,EW,EXC,EXE,EXPD,EXPE,EXR,F,FANG,FAST,FBF-200403,FBIN,FBO-199603,FCN-199810,FCX,FDC-200709,FDO-201507,FDS,FDX,FE,FFB-199512,FFIV,FG-199804,FHI,FHN,FICO,FIS,FISV,FITB,FIX,FJ-200011,FJCC-200809,FL-202509,FLIR-202105,FLMIQ-200408,FLR,FLS,FLTWQ-200907,FMC,FMCC,FMY-199905,FNB-199511,FNMA,FOSL,FOXA,FPC-200011,FRCB,FRM-199612,FRO-199909,FRT,FRX-201406,FSH-200611,FSL.B-200612,FSLR,FTI,FTL-200004,FTNT,FTRCQ-202104,FTV,FWLT-201412,G-200509,GAP,GAPTQ-201203,GAS-201606,GBLXQ-200312,GCO,GD,GDDY,GDT-200604,GDW-200609,GE,GEB-199408,GEHC,GEN,GENZ-201104,GEV,GFS.A-199810,GGP-201808,GHC-199308,GIC-200001,GIDL-199709,GILD,GIS,GL,GLD-199705,GLK-200507,GLW,GM,GMCR-201603,GME,GNE-199906,GNN-199006,GNRC,GNT-199806,GNW,GOOGL,GOSHA-200507,GP-200512,GPC,GPN,GPU-200111,GQ-199404,GR-201207,GRA-202109,GRMN,GRN-199812,GS,GSX-199810,GT,GTE-200006,GTW-200710,GWF-199707,GWOW-201009,GWW,H-200704,HAL,HAR-201703,HAS,HBAN,HBI-202511,HBJ-199111,HBOC-199901,HCA,HCBK-201510,HCR-200712,HD,HDLM-201301,HES-202507,HET-200801,HFS-199712,HI-200303,HIA-199002,HIG,HII,HLT,HM-200112,HMA-201401,HNZ-201306,HOG,HOLX,HON,HOOD,HOT-201609,HP,HPC-200811,HPE,HPQ,HRB,HRL,HRZIQ-200107,HSH-201408,HSIC,HSP-201509,HST,HSY,HTMXQ-201305,HUBB,HUM,HWM,I-199603,IAC,IBKR,IBM,ICE,IDXX,IEX,IFF,IGT-201504,IK-199902,IKN-200810,ILMN,IMNX-200207,INCLF-200701,INCY,INFO-202202,INGR-200611,INTC,INTU,INVH,IP,IPG-202511,IPGP,IQV,IR,IRM,ISRG,ISS-199206,IT,ITT,ITW,IVZ,J,JAVA-201001,JBHT,JBL,JCI,JEF,JH-200705,JHF-200404,JKHY,JNJ,JNPR-202507,JNS-201705,JNY-201404,JOS-200005,JOY-201704,JP-200603,JPM,JWN-202505,JWP-199310,K-202512,KATE-201707,KBH,KDP,KEY,KEYS,KG-201102,KHC,KIM,KKR,KLAC,KM-200212,KMB,KMG-200608,KMI,KMX,KO,KR,KRB-200512,KRFT-201507,KRI-200606,KSE-200708,KSS,KSU-202112,KVUE,KWP-199911,L,LCE-199404,LDG-200810,LDOS,LDW-200012,LEG,LEHMQ-201203,LEN,LH,LHX,LIFE-201402,LII,LIN,LINB-199510,LIT-200105,LKQ,LLL-201906,LLTC-201703,LLX-199710,LLY,LM-202007,LMT,LNC,LNT,LO-201506,LOR-199604,LOTS-199507,LOW,LPX,LRCX,LSI-201405,LU-200611,LUB-202205,LULU,LUMN,LUV,LVLT-201710,LVS,LW,LXK-201611,LYB,LYV,M,MA,MAA,MAC,MAI-199506,MAR,MAS,MAT,MAY-200508,MBI,MCA-199101,MCAWA-199409,MCD,MCHP,MCIC-199809,MCK,MCO,MD-199707,MDLZ,MDP-202112,MDRIQ-202006,MDT,MEA-200201,MEDI-200706,MEE-201106,MEL-200706,MER-200812,MERQ-200611,MET,META,MFE-201102,MGM,MHC-199112,MHK,MHS-201203,MI-201107,MII-199906,MIL-201007,MIR-201012,MJN-201706,MKC,MKG-200010,MKTX,ML-199503,MLM,MMI-201205,MMM,MNKKQ-202206,MNST,MO,MOB-199911,MOH,MOLX-201312,MON-201806,MOS,MPC,MPWR,MRK,MRN-199606,MRNA,MRO-202411,MRSH,MS,MSCI,MSFT,MSI,MST-199808,MTB,MTCH,MTD,MTG,MTL-199909,MTLQQ-201103,MTW,MU,MUR,MWI-200402,MWV-201507,MWW-201610,MXIM-202108,MXS-199506,MYG-200603,MZIAQ-201302,NAE-199708,NAV-202106,NAVI,NBL-202010,NBR,NC,NCC-200812,NCE-200008,NCLH,NCR-199109,NDAQ,NDSN,NEBLQ-202102,NEC-199706,NEE,NEM,NEU,NFB-200611,NFLX,NFX-201902,NGH-200012,NI,NKE,NKTR,NL,NLC-199912,NLSN-202210,NMK-200201,NOC,NOV,NOVL-201104,NOW,NRG,NRT-199008,NRTLQ-201510,NSC,NSI-200306,NSM-201109,NTAP,NTRS,NUE,NVDA,NVLS-201206,NVR,NWL,NWSA,NXPI,NXTL-200508,NYN-199708,NYT,NYX-201311,O,OAT-200108,ODFL,ODP-202512,OGN,OI,OK-200103,OKE,OM-199709,OMC,OMX-201311,ON,ONE-200406,ORCL,ORLY,ORX-199902,OTIS,OWENQ-200610,OXY,PAC-199703,PALM-201006,PANW,PAS-201002,PAYC,PAYX,PBCT-202204,PBG-201002,PBI,PBY-201602,PCAR,PCG,PCH,PCI-199407,PCL-201602,PCLB-199310,PCP-201601,PCS-200404,PD-200703,PDCO-202504,PDG-200603,PDQ-199207,PEG,PEL-199706,PENN,PEP,PET-199806,PETM-201503,PFE,PFG,PG,PGL-200702,PGN-201207,PGR,PH,PHA-200304,PHB-199910,PHL-199008,PHM,PIN-199410,PKG,PLD-201106,PLL-201508,PLTR,PM,PMCS-201601,PMI-199911,PN-199109,PNC,PNR,PNU-200003,PNW,PODD,POM-201603,POOL,PPG,PPL,PPW-199911,PRD-200110,PRGO,PRSU,PRU,PSA,PSFT-200501,PSKY,PSX,PT-199505,PTC,PTV-201011,PVH,PVN-200509,PVT-199906,PWER-201307,PWJ-200011,PWR,PX-201810,PXD-202405,PYPL,PZE-199908,Q-201103,QCOM,QEP-202103,QLGC-201608,QRVO,QTRN-200309,R,RADCQ-202409,RAI-201707,RAL-200112,RATL-200302,RBD-199903,RBK-200601,RCL,RDC-201904,REG,REGN,RF,RHI,RHT-201907,RIG,RJF,RL,RLM-200005,RMD,RML-200608,RNB-199912,ROH-200904,ROK,ROL,ROP,ROST,RRC,RRD-202202,RSG,RSHCQ-201510,RTN-202004,RTX,RVTY,RX-201002,RYAN-200610,RYC-199908,RYI-200710,S-202003,SAF-200809,SAI-199812,SANM,SAPE-201502,SB-199711,SBAC,SBL-200701,SBNY,SBUX,SCG-201812,SCHW,SCI,SDH-200106,SDS-200508,SE-201702,SEBL-200601,SEDG,SEE,SEG-200011,SFA-200602,SFS-200008,SFX-199509,SGID-200610,SGP-200911,SHEL,SHLDQ-202210,SHOY-200204,SHW,SIAL-201511,SIG,SII-201008,SITC,SIVBQ-202411,SJM,SK-199805,SKY,SLB,SLG,SLM,SLR-200710,SMCI,SMI-200109,SMS-200007,SNA,SNC-199511,SNDK,SNI-201803,SNPS,SNT-199910,SNV-202512,SO,SOLS,SOLV,SOTR-200410,SOV-200901,SPC-199204,SPG,SPGI,SPLS-201709,SPP-199512,SPXC,SQD-199105,SRCL-202411,SRE,SRR-200708,SSP,STE,STI-201912,STJ-201701,STLD,STO-199811,STR-201609,STT,STX,STZ,SUB-200102,SUN-201210,SUNEQ-201712,SVU-201810,SW,SWK,SWKS,SWN-202409,SWY-201501,SXCL-201702,SYF,SYK,SYN-199410,SYY,T,TA-199907,TAP,TAP.B-200404,TCOMA-199903,TDC,TDG,TDM-199708,TDY,TE-201606,TECH,TEG-201506,TEK-200711,TEL,TEN-202211,TER,TEX,TFC,TFCFA-201903,TFX,TGNA,TGT,THC,THY-199708,TIC-199312,TIE-201301,TIF-202101,TIN-201202,TJX,TKA-199108,TKO,TKR,TLAB-201312,TMC-200006,TMO,TMUS,TNB-201205,TNL,TOS-200109,TOY-200507,TPL,TPR,TRB-200712,TRGP,TRIP,TRMB,TROW,TRV,TRW-200212,TSCO,TSG-200703,TSLA,TSN,TSS-201909,TT,TTD,TTWO,TUPBQ-202506,TWC-201605,TWTR-202210,TWX-201806,TX-200110,TXN,TXT,TXU-200710,TYL,UAA,UAL,UALAQ-200602,UAWGQ-200303,UBER,UCC-199904,UCL-200508,UCM-200010,UDR,UH-200005,UHS,UIS,UK-200102,ULTA,UMG-200006,UN-202011,UNH,UNM,UNP,UPC-200406,UPR-200007,UPS,URBN,URI,USB,USBC-199708,USG-201904,USH-199706,USHC-199607,USS-199810,UST-200901,USW-200006,UVN-200703,V,VALPQ-202104,VAR-202104,VAT-199609,VFC,VIAB-201912,VIAV,VICI,VLO,VLTO,VMC,VNO,VNT,VO-200012,VRSK,VRSN,VRTS-200507,VRTX,VST,VSTNQ-201010,VTR,VTRS,VTSS-201504,VYX,VZ,WAB,WAI-199808,WAMUQ-201203,WAN.B-199309,WAT,WB-200812,WBA-202508,WBD,WCG-202001,WCOEQ-200404,WDAY,WDC,WEC,WELL,WEN-200809,WETT-199210,WFC,WFM-201708,WFRD,WHR,WINMQ-202009,WLA-200006,WLBAQ-202004,WLL-200203,WLP-200411,WM,WMB,WMT,WNDXQ-200611,WOR,WPX-202101,WRB,WRK-202407,WSM,WST,WTW,WU,WWY-200810,WY,WYE-200910,WYNN,X-202506,XEC-202109,XEL,XL-201809,XLNX-202202,XOM,XRAY,XRX,XTO-201006,XYL,XYZ,YELLQ,YNR-200010,YUM,ZBH,ZBRA,ZE-199805,ZION,ZRN-199806,ZTS
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2015-01-31,-0.000959,0.363116,0.226878,NaN,0.166801,0.181371,NaN,0.162945,NaN,NaN,0.414704,NaN,NaN,0.106624,-0.045493,0.028490,NaN,0.113123,NaN,NaN,NaN,0.004688,NaN,0.040524,0.174016,0.192767,0.063230,0.048117,0.140319,0.103832,-0.114516,0.096969,-0.006037,NaN,NaN,0.228731,NaN,0.030424,NaN,0.155821,0.051100,0.025457,0.030643,-0.292720,NaN,-0.164257,-0.002322,0.234075,0.187948,-0.018744,0.071430,0.169061,NaN,0.108929,-0.505597,NaN,-0.450622,0.010146,0.032758,0.305527,NaN,0.106674,0.101587,NaN,NaN,-0.045447,NaN,0.245360,NaN,-0.026473,-0.400813,-0.798208,0.078357,NaN,0.057205,0.135007,-0.467500,-0.276971,NaN,0.125481,0.115479,-0.110946,0.087571,NaN,0.063499,NaN,NaN,0.151682,-0.087397,0.065855,NaN,NaN,0.102837,NaN,NaN,NaN,NaN,0.118057,NaN,0.057585,-0.101382,NaN,0.154192,0.340664,-0.432023,0.026614,NaN,NaN,0.087557,0.688626,-0.013750,NaN,0.015273,NaN,0.143701,-0.525269,0.033240,0.157822,0.087989,0.027706,NaN,0.283272,NaN,0.398764,0.239874,0.201669,-0.136721,0.155808,NaN,0.171414,NaN,-0.029994,NaN,-0.063125,0.016923,NaN,NaN,0.191881,NaN,0.010611,NaN,NaN,-0.121076,0.007075,NaN,0.088176,NaN,-0.053606,-0.277890,-0.085069,0.123425,NaN,NaN,NaN,NaN,NaN,0.119805,0.216989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.160621,0.170918,NaN,NaN,0.075948,NaN,0.414189,0.036899,NaN,-0.734253,NaN,NaN,-0.466572,-0.166506,NaN,0.041362,NaN,0.129743,0.139136,0.074980,0.216180,0.172166,0.121299,-0.304211,0.105478,NaN,-0.157756,0.126065,NaN,NaN,NaN,NaN,0.261130,0.066701,NaN,NaN,NaN,-0.066375,0.073423,0.022651,0.198204,NaN,NaN,0.081229,0.101576,NaN,NaN,0.264297,NaN,NaN,0.226009,0.136690,NaN,NaN,NaN,0.291171,NaN,NaN,NaN,0.128200,NaN,-0.398957,NaN,0.170862,0.050718,0.112392,NaN,-0.109679,NaN,0.093820,NaN,NaN,0.025491,-0.723111,0.146684,-0.060197,NaN,0.081732,0.080591,0.256004,0.144336,-0.057023,0.126600,NaN,NaN,-0.030297,0.317359,NaN,NaN,-0.066991,-0.018471,-0.306215,NaN,NaN,0.006894,NaN,0.085689,NaN,0.179156,-0.197928,0.222160,0.213363,0.199119,0.137032,0.120712,-0.026134,NaN,NaN,-0.334044,NaN,-0.165876,0.014631,0.055953,0.075915,-0.090791,0.173187,0.020957,NaN,NaN,0.127915,NaN,0.149253,NaN,NaN,0.171484,0.234755,0.150808,NaN,NaN,-0.141101,0.073874,NaN,NaN,0.019787,NaN,0.172745,-0.044074,NaN,NaN,NaN,NaN,0.252108,-0.133957,-0.370612,-0.226441,NaN,NaN,-0.278380,0.089456,0.243950,NaN,NaN,NaN,NaN,NaN,0.071950,-0.009324,NaN,0.053122,NaN,0.105350,0.062835,0.209098,NaN,0.144285,0.034040,0.087387,NaN,NaN,-0.117938,0.106625,-0.073589,0.113334,NaN,0.152959,0.256443,0.070894,0.100399,-0.809937,0.087745,-0.259405,-0.228218,-0.104612,NaN,0.259378,0.124555,0.259798,0.121016,0.019685,0.139561,0.046206,-0.252585,NaN,0.005041,0.327899,NaN,-0.136821,NaN,0.270565,0.114270,NaN,NaN,-0.057651,NaN,0.155000,NaN,NaN,0.115104,0.069397,0.080868,0.131965,NaN,0.031686,0.162235,0.129136,0.002802,-0.131550,-0.058133,0.029551,0.513629,NaN,NaN,-0.235347,NaN,NaN,0.087487,NaN,0.114719,0.146096,-0.344482,0.204148,0.140477,0.199884,0.124336,NaN,0.131795,-0.113001,0.085190,NaN,NaN,0.183162,0.095372,0.394690,0.034378,NaN,0.017204,0.084610,0.113245,-0.090386,-0.395715,-0.028312,NaN,0.130903,NaN,NaN,-0.428114,NaN,0.184268,0.163057,0.139731,0.137446,NaN,0.157619,NaN,0.079768,0.143255,0.126310,0.135887,0.162594,-0.033986,0.088028,NaN,NaN,0.110782,-0.066174,NaN,-0.231740,-0.212354,NaN,-0.216586,-0.627961,NaN,NaN,-0.643262,0.057807,NaN,NaN,-0.047691,NaN,NaN,0.112239,NaN,NaN,NaN,-0.465903,NaN,NaN,0.198897,0.163127,NaN,-0.213504,NaN,0.023410,NaN,0.009374,NaN,-0.069445,0.176660,NaN,NaN,NaN,-0.021410,NaN,NaN,0.125766,NaN,NaN,NaN,0.196520,NaN,NaN,NaN,0.128301,0.030833,-0.003424,NaN,NaN,0.053329,-0.021450,0.064532,-0.164876,NaN,NaN,-0.041472,NaN,-0.716404,-0.096926,NaN,NaN,0.205923,0.103235,NaN,NaN,NaN,0.009057,-0.124412,NaN,0.152641,NaN,0.032955,NaN,NaN,NaN,NaN,0.011305,NaN,-0.584132,-0.000561,0.051926,0.108715,0.131490,NaN,NaN,0.263673,0.037421,NaN,0.269523,NaN,-0.286081,NaN,NaN,NaN,NaN,0.161235,0.178640,0.113099,NaN,NaN,NaN,-0.049745,0.053382,0.082419,NaN,0.027656,-0.528756,NaN,NaN,0.183540,0.016695,0.062331,NaN,NaN,0.137537,0.175909,0.097154,0.076665,NaN,-0.132952,0.121467,0.062327,NaN,-0.119529,0.232593,-0.109350,0.155485,0.104409,-0.028806,-0.019122,0.093913,NaN,NaN,0.033270,NaN,NaN,0.258787,-0.020596,NaN,0.173952,0.140600,NaN,0.088802,0.072054,0.085217,0.099583,NaN,0.147153,0.250337,NaN,0.177417,-0.167989,0.089126,0.058335,-0.175811,NaN,0.137755,0.051319,-0.030514,-0.151376,NaN,NaN,0.051955,0.012755,-0.085992,0.268977,NaN,NaN,-0.273298,NaN,0.096257,0.164977,NaN,0.011120,-0.175215,-0.117979,0.214150,-0.020899,NaN,NaN,NaN,0.119307,0.001253,0.198878,NaN,0.095626,NaN,0.177049,0.246968,0.010837,0.268079,NaN,0.071357,NaN,NaN,0.160678,0.131395,NaN,NaN,-0.043375,NaN,NaN,0.144562,NaN,0.233808,NaN,0.067255,0.052318,-0.039859,NaN,0.066586,NaN,NaN,NaN,0.052192,0.055057,-0.019349,NaN,0.119353,0.045658,0.196279,0.120485,0.104377,0.051885,NaN,NaN,0.369423,0.097607,0.165072,NaN,NaN,-0.256430,0.320787,0.115697,0.457995,0.117403,-0.253313,NaN,-0.138708,-0.192892,0.055920,0.135471,0.162241,0.043047,0.241731,NaN,0.202204,0.130661,-0.207505,NaN,-0.146032,NaN,NaN,-0.055049,-0.063102,NaN,0.111041,0.094759,NaN,-0.026456,0.133795,-1.022476,0.138192,NaN,NaN,NaN,NaN,NaN,NaN,-0.013534,0.147954,NaN,-0.210908,NaN,0.116031,NaN,NaN,NaN,NaN,NaN,0.083753,0.053079,NaN,0.287863,NaN,-0.173570,NaN,0.148592,0.213146,0.422264,0.183340,NaN,0.181836,NaN,-0.035175,-0.069104,0.156144,0.167211,-0.003694,NaN,NaN,-0.332462,0.110381,0.188368,0.038135,0.120389,0.018568,NaN,0.023809,NaN,0.177848,0.008621,NaN,NaN,-0.392938,0.060642,-0.262195,NaN,0.014360,-0.347543,-0.040380,NaN,NaN,NaN,NaN,-0.112859,0.214824,-0.484664,-0.809301,0.168746,NaN,NaN,0.388711,NaN,0.223333,-0.022488,-0.537777,NaN,0.051076,-0.294867,0.035084,NaN,-0.254468,-0.488453,NaN,0.088206,0.220873,0.189834,-0.077176,NaN,-0.067693,NaN,0.219136,-0.215897,NaN,0.090810,-0.313015,NaN,-0.555526,0.072686,NaN,NaN,0.135220,0.058135,0.010270,0.086936,NaN,0.102921,0.216119,-0.134009,0.143604,NaN,NaN,-0.134322,NaN,0.095750,NaN,0.198212,0.410141,NaN,-0.249543,NaN,-0.294144,NaN,0.097730,NaN,0.102841,NaN,0.109951,0.246092,NaN,NaN,NaN,-0.141322,NaN,NaN,0.379653,NaN,0.590373,0.122604,0.023241,NaN,-0.110541,-0.154442,0.100983,0.121757,0.028738,NaN,-0.031114,NaN,-0.046465,NaN,NaN,0.206655,NaN,NaN,0.034333,NaN,0.123077,0.070439,NaN,0.312647,0.065748,0.041156,0.163196,NaN,NaN,0.062293,0.034341,NaN,NaN,NaN,0.068987,NaN,0.098870,NaN,0.177093,NaN,-0.010708,0.185383,NaN,NaN,0.035488,-0.073556,NaN,0.186499,0.149350,-0.000455,0.122379,0.101889,0.043724,NaN,NaN,0.138369,0.120333,0.031682,0.091550,NaN,-0.110563,-0.102009,NaN,-0.057007,NaN,0.095240,NaN,NaN,NaN,NaN,-0.197239,-0.015000,-0.434108,NaN,NaN,NaN,-0.052116,-0.532895,0.277722,NaN,NaN,0.060885,0.047661,0.084616,NaN,NaN,NaN,NaN,0.401865,-0.306532,0.151877,0.373194,0.004143,0.207982,0.223903,-0.853173,0.127653,0.146894,NaN,0.112684,NaN,NaN,NaN,-0.107262,0.108396,0.071194,0.359285,-0.485285,0.021516,0.072388,-0.985111,0.165179,0.007199,-0.065454,NaN,NaN,NaN,NaN,-0.720481,NaN,NaN,0.032393,0.426279,NaN,0.079456,NaN,-0.001745,0.066082,0.134847,0.118563,0.099455,NaN,NaN,-0.139212,NaN,NaN,0.223373,NaN,NaN,NaN,NaN,NaN,NaN,-0.182142,-0.119613,NaN,0.244954,0.305991,0.176979,NaN,0.058527,-0.004727,-0.041491,NaN,-0.014089,-0.314495,0.094083,0.203947,NaN,0.322296,NaN,NaN,0.150399,NaN,NaN,-0.070046,0.113136,NaN,0.112163,0.102266,NaN,NaN,NaN,NaN,NaN,0.105970,0.076299,0.530066,NaN,-0.222385,NaN,0.101570,0.074055,NaN,0.054714,0.200635,0.055146,-0.054381,0.105978,NaN,0.035677,0.162340,0.173343,0.107888,NaN,NaN,-0.147023,0.165556,0.004329,0.101104,0.441439,-0.510972,0.035750,-0.328583,NaN,0.119556,NaN,0.080939,-0.025394,NaN,0.014752,NaN,NaN,0.083023,0.160349,NaN,0.055740,0.127160,0.004913,0.109866,NaN,0.031725,-0.148913,0.015596,-0.384845,-0.000834,0.092027,0.089944,0.031555,0.286605,0.076464,NaN,NaN,NaN,0.071305,NaN,0.260839,NaN,0.052445,-0.117723,NaN,NaN,0.062339,-0.221509,NaN,0.133174,NaN,NaN,-0.305177,0.112740,NaN,-0.263852,-0.375279,-0.330913,0.027775,0.129081,NaN,0.270942,NaN,-0.076366,0.070155,0.084302,0.022153,NaN,0.231383,-0.263959,0.042049,-0.132939,0.203566,NaN,0.125602,0.096109,NaN,0.182212,0.132228,0.487772,NaN,NaN,NaN,NaN,NaN,NaN,0.092390,NaN,0.151869,0.175291,NaN,0.335425,NaN,-0.095186,0.220352,0.012950,0.186359,NaN,NaN,0.092784,0.036821,-0.026315,0.048176,NaN,-0.073674,NaN,NaN,NaN,NaN,NaN,NaN,0.222453,-0.580028,0.039734,NaN,0.181365,-0.133332,0.095529,NaN,-0.001226,NaN,0.032419,0.111464,NaN,NaN,0.064986,0.155116,NaN,0.226939,NaN,NaN,0.134150,0.089191,0.091350,-0.185804,-0.023092,0.052163,NaN,NaN,NaN,0.076294,NaN,0.038018,-0.096635,0.094506,NaN,-0.096301,0.189443,0.133864,0.212149,NaN,NaN,0.055660,0.272622,-0.697505,0.339660,-0.138025,NaN,-0.071731,NaN,NaN,0.153115,-0.236793,0.146668,NaN,-0.348520,-0.720709,0.125674,NaN,0.062706,0.237825,0.048220,0.046684,NaN,0.098257,NaN,-0.312573,0.029326,-0.300069,0.126469,0.058166,-0.075221,-0.071143,0.120481,0.117244,NaN,-0.019161,NaN,-0.223055,NaN,-0.097943,0.092145,-0.061498,NaN,-0.030326,NaN,0.291838

> <u>Comentario</u>: Tras filtrar al periodo de backtest (desde 2015-01-01), el número de meses con señal válida es coherente con 12 y 6 meses de ventana más el shift.

## <font color=#0099CC>**4. Z-SCORES Y SCORE COMPUESTO**</font>

### <font color=#336699>**4.1. Estandarización transversal**</font>

Las volatilidades de las ventanas de 6 y 12 meses no son directamente comparables en nivel, por lo que se estandarizan los retornos **dentro del universo de cada mes**.

La estandarización transversal se define como:

$$
Z_{i,t} = \frac{x_{i,t} - \mu_t}{\sigma_t}
$$

donde:

- x(i,t) es el valor del activo (i) en la fecha (t),
- mu(t) es la media transversal en la fecha (t),
- sigma(t) es la desviación típica transversal en la fecha (t).

Se calculan así:

$$
Z_{6,i,t} = \frac{R_{6,i,t} - \mu_{6,t}}{\sigma_{6,t}}
$$

$$
Z_{12,i,t} = \frac{R_{12,i,t} - \mu_{12,t}}{\sigma_{12,t}}
$$

El **score final compuesto** se define como la media simple de ambos z-scores:

$$
Score_{i,t} = \frac{Z_{6,i,t} + Z_{12,i,t}}{2}
$$

Esta construcción sigue la metodología utilizada en índices de momentum como los de MSCI.

In [14]:
# Cálculo de Z-scores y score compuesto por mes

# Aplicar máscara de universo (fuera del universo => NaN)
mom_12_u = mom_12.where(universe_mask_bt)
mom_6_u = mom_6.where(universe_mask_bt)

# Medias y desviaciones transversales (por fecha)
mean_12 = mom_12_u.mean(axis=1)
std_12 = mom_12_u.std(axis=1, ddof=0)
mean_6 = mom_6_u.mean(axis=1)
std_6 = mom_6_u.std(axis=1, ddof=0)

# Evitar divisiones por cero
std_12 = std_12.replace(0, np.nan)
std_6 = std_6.replace(0, np.nan)

z_12 = (mom_12_u.sub(mean_12, axis=0)).div(std_12, axis=0)
z_6 = (mom_6_u.sub(mean_6, axis=0)).div(std_6, axis=0)

score = (z_12 + z_6) / 2.0

print('> Z-scores y score compuesto calculados')
display(score.head())

> Z-scores y score compuesto calculados

symbol,A,AABA-201910,AAL,AAMRQ-201312,AAP,AAPL,AAV-199901,ABBV,ABI-200811,ABKFQ-201304,ABMD-202212,ABNB,ABS-200606,ABT,ACAS-201701,ACGL,ACKH-200712,ACN,ACS-201002,ACV-201105,ACY-199411,ADBE,ADCT-201012,ADI,ADM,ADP,ADSK,ADT-201604,AEE,AEP,AES,AET-201811,AFL,AFS-200011,AGC-200108,AGN-201503,AHM-199810,AIG,AIT-199910,AIV,AIZ,AJG,AKAM,AKS-202003,AL-200711,ALB,ALGN,ALK,ALL,ALLE,ALTR-201512,ALXN-202107,AM-201308,AMAT,AMCC-201701,AMCR,AMD,AME,AMG,AMGN,AMH-199709,AMP,AMT,AMTM,AMX-199311,AMZN,AN-199812,ANDV-201809,ANDW-200712,ANET,ANF,ANRZQ-201607,ANSS-202507,ANV-199904,AON,AOS,APA,APC-201908,APCC-200702,APD,APH,APO,APOL-201702,APP,APTV,AR-199911,ARC-200004,ARE,ARES,ARG-201605,AS-199909,ASC-199906,ASH,ASN-200710,ASND-199906,ASO-200611,AT-200711,ATGE,ATI-199906,ATO,ATVI-202310,AV-200710,AVB,AVGO,AVP-202001,AVY,AW-200812,AWE-200410,AWK,AXON,AXP,AYE-201102,AYI,AZA-200106,AZO,B,BA,BAC,BALL,BAX,BAY-199808,BBBYQ-202309,BBI-199801,BBWI,BBY,BC,BCO,BCR-201712,BDK-201003,BDX,BEAM-201404,BEN,BEV-200603,BF.B,BFH,BFI-199907,BFO-200010,BG,BGEN-200311,BGGSQ-202101,BHF,BHMSQ-200401,BIGGQ,BIO,BJS-201004,BK,BKB-199909,BKNG,BKR,BLDR,BLK,BLS-200612,BLY-199612,BMC-201309,BMET-200709,BMG-200101,BMS-201906,BMY,BN-199503,BNI-201002,BNL-199806,BNSSA-201206,BOAT-199701,BOL-200710,BR-200603,BRCM-201601,BRK.B,BRL-200812,BRNO-199508,BRO,BSC-200805,BSET,BSX,BT-199906,BTUUQ-201704,BUD-200811,BV-199409,BVSN-202005,BWA,BWY-199510,BX,BXLT-201606,BXP,C,CA-201811,CAG,CAH,CAL,CAM-201604,CAR,CARR,CAT,CB-201601,CBB-199801,CBE-201211,CBH-200803,CBL-199010,CBOE,CBRE,CBS-200005,CBSS-200709,CCB-199602,CCEP,CCI,CCK,CCL,CCTYQ-201109,CCU-200807,CDNS,CDW,CE-200402,CEG,CELG-201911,CEN-200711,CEPH-201110,CERN-202206,CF,CFC-200806,CFG,CFL-199804,CFN-201503,CG-200011,CGP-200101,CHA-200006,CHD,CHIR-200604,CHKAQ-202102,CHRS-201206,CHRW,CHTR,CI,CIC-199505,CIEN,CIN-200603,CINF,CITGQ-200912,CKL-199505,CL,CLF,CLX,CMA,CMB-199603,CMCSA,CMCSK-201512,CME,CMG,CMI,CMS,CMVT-201302,CMX-200703,CNA,CNC,CNCEQ-200309,CNG-200001,CNP,CNW-201510,CNX,CNXT-201104,COC-200208,COF,COIN,COL-201811,COMS-201004,COO,COP,COR,COST,COTY,COV-201501,CPAY,CPB,CPGX-201606,CPNLQ-200802,CPPRQ-202102,CPQ-200205,CPRI,CPRT,CPT,CPWR-201412,CRH,CRL,CRM,CRR-199706,CRWD,CSCO,CSE-199911,CSGP,CSR-200006,CSRA-201804,CSX,CTAS,CTB-202106,CTCO-199110,CTLT-202412,CTRA,CTSH,CTVA,CTX-200908,CTXS-202209,CUE-199309,CVC-201606,CVG-201810,CVGQE-200412,CVH-201305,CVN-199112,CVNA,CVS,CVX,CXO-202101,CXT,CYM-199912,CYR-199606,CZR,D,DAL,DASH,DAY,DCNAQ-200801,DD,DDOG,DDS,DE,DEC-199806,DECK,DELL-201310,DFODQ-202106,DFS-202505,DG,DGN-199910,DGX,DHI,DHR,DI-199809,DIGI-199809,DINO,DIS,DISCK-202204,DISH-202312,DJ-200712,DLR,DLTR,DLX,DNB-201902,DNRCQ-202009,DOC,DOFSQ-202104,DOV,DOW-201708,DPHIQ-200910,DPZ,DRE-202209,DRI,DTE,DTV-201507,DUK,DVA,DVN,DWD-199705,DXC,DXCM,DYHGQ-200012,DYN-201804,E-199504,EA,EBAY,EC-200606,ECH-199807,ECL,ECO-200301,ED,EDS-200808,EFU-200011,EFX,EG,EHC,EIX,EKDKQ-201309,EL,ELV,EMC-201609,EME,EMN,EMR,ENDPQ-202405,ENPH,ENRNQ-200411,ENS-199708,EOG,EOP-200702,EP-201205,EPAM,EQ-200906,EQIX,EQR,EQT,ERIE,ES,ESRX-201812,ESS,ESY-199505,ETFC-202010,ETN,ETR,ETS-200603,ETSY,EVHC-201810,EVRG,EW,EXC,EXE,EXPD,EXPE,EXR,F,FANG,FAST,FBF-200403,FBIN,FBO-199603,FCN-199810,FCX,FDC-200709,FDO-201507,FDS,FDX,FE,FFB-199512,FFIV,FG-199804,FHI,FHN,FICO,FIS,FISV,FITB,FIX,FJ-200011,FJCC-200809,FL-202509,FLIR-202105,FLMIQ-200408,FLR,FLS,FLTWQ-200907,FMC,FMCC,FMY-199905,FNB-199511,FNMA,FOSL,FOXA,FPC-200011,FRCB,FRM-199612,FRO-199909,FRT,FRX-201406,FSH-200611,FSL.B-200612,FSLR,FTI,FTL-200004,FTNT,FTRCQ-202104,FTV,FWLT-201412,G-200509,GAP,GAPTQ-201203,GAS-201606,GBLXQ-200312,GCO,GD,GDDY,GDT-200604,GDW-200609,GE,GEB-199408,GEHC,GEN,GENZ-201104,GEV,GFS.A-199810,GGP-201808,GHC-199308,GIC-200001,GIDL-199709,GILD,GIS,GL,GLD-199705,GLK-200507,GLW,GM,GMCR-201603,GME,GNE-199906,GNN-199006,GNRC,GNT-199806,GNW,GOOGL,GOSHA-200507,GP-200512,GPC,GPN,GPU-200111,GQ-199404,GR-201207,GRA-202109,GRMN,GRN-199812,GS,GSX-199810,GT,GTE-200006,GTW-200710,GWF-199707,GWOW-201009,GWW,H-200704,HAL,HAR-201703,HAS,HBAN,HBI-202511,HBJ-199111,HBOC-199901,HCA,HCBK-201510,HCR-200712,HD,HDLM-201301,HES-202507,HET-200801,HFS-199712,HI-200303,HIA-199002,HIG,HII,HLT,HM-200112,HMA-201401,HNZ-201306,HOG,HOLX,HON,HOOD,HOT-201609,HP,HPC-200811,HPE,HPQ,HRB,HRL,HRZIQ-200107,HSH-201408,HSIC,HSP-201509,HST,HSY,HTMXQ-201305,HUBB,HUM,HWM,I-199603,IAC,IBKR,IBM,ICE,IDXX,IEX,IFF,IGT-201504,IK-199902,IKN-200810,ILMN,IMNX-200207,INCLF-200701,INCY,INFO-202202,INGR-200611,INTC,INTU,INVH,IP,IPG-202511,IPGP,IQV,IR,IRM,ISRG,ISS-199206,IT,ITT,ITW,IVZ,J,JAVA-201001,JBHT,JBL,JCI,JEF,JH-200705,JHF-200404,JKHY,JNJ,JNPR-202507,JNS-201705,JNY-201404,JOS-200005,JOY-201704,JP-200603,JPM,JWN-202505,JWP-199310,K-202512,KATE-201707,KBH,KDP,KEY,KEYS,KG-201102,KHC,KIM,KKR,KLAC,KM-200212,KMB,KMG-200608,KMI,KMX,KO,KR,KRB-200512,KRFT-201507,KRI-200606,KSE-200708,KSS,KSU-202112,KVUE,KWP-199911,L,LCE-199404,LDG-200810,LDOS,LDW-200012,LEG,LEHMQ-201203,LEN,LH,LHX,LIFE-201402,LII,LIN,LINB-199510,LIT-200105,LKQ,LLL-201906,LLTC-201703,LLX-199710,LLY,LM-202007,LMT,LNC,LNT,LO-201506,LOR-199604,LOTS-199507,LOW,LPX,LRCX,LSI-201405,LU-200611,LUB-202205,LULU,LUMN,LUV,LVLT-201710,LVS,LW,LXK-201611,LYB,LYV,M,MA,MAA,MAC,MAI-199506,MAR,MAS,MAT,MAY-200508,MBI,MCA-199101,MCAWA-199409,MCD,MCHP,MCIC-199809,MCK,MCO,MD-199707,MDLZ,MDP-202112,MDRIQ-202006,MDT,MEA-200201,MEDI-200706,MEE-201106,MEL-200706,MER-200812,MERQ-200611,MET,META,MFE-201102,MGM,MHC-199112,MHK,MHS-201203,MI-201107,MII-199906,MIL-201007,MIR-201012,MJN-201706,MKC,MKG-200010,MKTX,ML-199503,MLM,MMI-201205,MMM,MNKKQ-202206,MNST,MO,MOB-199911,MOH,MOLX-201312,MON-201806,MOS,MPC,MPWR,MRK,MRN-199606,MRNA,MRO-202411,MRSH,MS,MSCI,MSFT,MSI,MST-199808,MTB,MTCH,MTD,MTG,MTL-199909,MTLQQ-201103,MTW,MU,MUR,MWI-200402,MWV-201507,MWW-201610,MXIM-202108,MXS-199506,MYG-200603,MZIAQ-201302,NAE-199708,NAV-202106,NAVI,NBL-202010,NBR,NC,NCC-200812,NCE-200008,NCLH,NCR-199109,NDAQ,NDSN,NEBLQ-202102,NEC-199706,NEE,NEM,NEU,NFB-200611,NFLX,NFX-201902,NGH-200012,NI,NKE,NKTR,NL,NLC-199912,NLSN-202210,NMK-200201,NOC,NOV,NOVL-201104,NOW,NRG,NRT-199008,NRTLQ-201510,NSC,NSI-200306,NSM-201109,NTAP,NTRS,NUE,NVDA,NVLS-201206,NVR,NWL,NWSA,NXPI,NXTL-200508,NYN-199708,NYT,NYX-201311,O,OAT-200108,ODFL,ODP-202512,OGN,OI,OK-200103,OKE,OM-199709,OMC,OMX-201311,ON,ONE-200406,ORCL,ORLY,ORX-199902,OTIS,OWENQ-200610,OXY,PAC-199703,PALM-201006,PANW,PAS-201002,PAYC,PAYX,PBCT-202204,PBG-201002,PBI,PBY-201602,PCAR,PCG,PCH,PCI-199407,PCL-201602,PCLB-199310,PCP-201601,PCS-200404,PD-200703,PDCO-202504,PDG-200603,PDQ-199207,PEG,PEL-199706,PENN,PEP,PET-199806,PETM-201503,PFE,PFG,PG,PGL-200702,PGN-201207,PGR,PH,PHA-200304,PHB-199910,PHL-199008,PHM,PIN-199410,PKG,PLD-201106,PLL-201508,PLTR,PM,PMCS-201601,PMI-199911,PN-199109,PNC,PNR,PNU-200003,PNW,PODD,POM-201603,POOL,PPG,PPL,PPW-199911,PRD-200110,PRGO,PRSU,PRU,PSA,PSFT-200501,PSKY,PSX,PT-199505,PTC,PTV-201011,PVH,PVN-200509,PVT-199906,PWER-201307,PWJ-200011,PWR,PX-201810,PXD-202405,PYPL,PZE-199908,Q-201103,QCOM,QEP-202103,QLGC-201608,QRVO,QTRN-200309,R,RADCQ-202409,RAI-201707,RAL-200112,RATL-200302,RBD-199903,RBK-200601,RCL,RDC-201904,REG,REGN,RF,RHI,RHT-201907,RIG,RJF,RL,RLM-200005,RMD,RML-200608,RNB-199912,ROH-200904,ROK,ROL,ROP,ROST,RRC,RRD-202202,RSG,RSHCQ-201510,RTN-202004,RTX,RVTY,RX-201002,RYAN-200610,RYC-199908,RYI-200710,S-202003,SAF-200809,SAI-199812,SANM,SAPE-201502,SB-199711,SBAC,SBL-200701,SBNY,SBUX,SCG-201812,SCHW,SCI,SDH-200106,SDS-200508,SE-201702,SEBL-200601,SEDG,SEE,SEG-200011,SFA-200602,SFS-200008,SFX-199509,SGID-200610,SGP-200911,SHEL,SHLDQ-202210,SHOY-200204,SHW,SIAL-201511,SIG,SII-201008,SITC,SIVBQ-202411,SJM,SK-199805,SKY,SLB,SLG,SLM,SLR-200710,SMCI,SMI-200109,SMS-200007,SNA,SNC-199511,SNDK,SNI-201803,SNPS,SNT-199910,SNV-202512,SO,SOLS,SOLV,SOTR-200410,SOV-200901,SPC-199204,SPG,SPGI,SPLS-201709,SPP-199512,SPXC,SQD-199105,SRCL-202411,SRE,SRR-200708,SSP,STE,STI-201912,STJ-201701,STLD,STO-199811,STR-201609,STT,STX,STZ,SUB-200102,SUN-201210,SUNEQ-201712,SVU-201810,SW,SWK,SWKS,SWN-202409,SWY-201501,SXCL-201702,SYF,SYK,SYN-199410,SYY,T,TA-199907,TAP,TAP.B-200404,TCOMA-199903,TDC,TDG,TDM-199708,TDY,TE-201606,TECH,TEG-201506,TEK-200711,TEL,TEN-202211,TER,TEX,TFC,TFCFA-201903,TFX,TGNA,TGT,THC,THY-199708,TIC-199312,TIE-201301,TIF-202101,TIN-201202,TJX,TKA-199108,TKO,TKR,TLAB-201312,TMC-200006,TMO,TMUS,TNB-201205,TNL,TOS-200109,TOY-200507,TPL,TPR,TRB-200712,TRGP,TRIP,TRMB,TROW,TRV,TRW-200212,TSCO,TSG-200703,TSLA,TSN,TSS-201909,TT,TTD,TTWO,TUPBQ-202506,TWC-201605,TWTR-202210,TWX-201806,TX-200110,TXN,TXT,TXU-200710,TYL,UAA,UAL,UALAQ-200602,UAWGQ-200303,UBER,UCC-199904,UCL-200508,UCM-200010,UDR,UH-200005,UHS,UIS,UK-200102,ULTA,UMG-200006,UN-202011,UNH,UNM,UNP,UPC-200406,UPR-200007,UPS,URBN,URI,USB,USBC-199708,USG-201904,USH-199706,USHC-199607,USS-199810,UST-200901,USW-200006,UVN-200703,V,VALPQ-202104,VAR-202104,VAT-199609,VFC,VIAB-201912,VIAV,VICI,VLO,VLTO,VMC,VNO,VNT,VO-200012,VRSK,VRSN,VRTS-200507,VRTX,VST,VSTNQ-201010,VTR,VTRS,VTSS-201504,VYX,VZ,WAB,WAI-199808,WAMUQ-201203,WAN.B-199309,WAT,WB-200812,WBA-202508,WBD,WCG-202001,WCOEQ-200404,WDAY,WDC,WEC,WELL,WEN-200809,WETT-199210,WFC,WFM-201708,WFRD,WHR,WINMQ-202009,WLA-200006,WLBAQ-202004,WLL-200203,WLP-200411,WM,WMB,WMT,WNDXQ-200611,WOR,WPX-202101,WRB,WRK-202407,WSM,WST,WTW,WU,WWY-200810,WY,WYE-200910,WYNN,X-202506,XEC-202109,XEL,XL-201809,XLNX-202202,XOM,XRAY,XRX,XTO-201006,XYL,XYZ,YELLQ,YNR-200010,YUM,ZBH,ZBRA,ZE-199805,ZION,ZRN-199806,ZTS
date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2015-01-31,-0.383775,1.135238,NaN,NaN,NaN,0.938448,NaN,0.652803,NaN,NaN,NaN,NaN,NaN,0.342973,NaN,NaN,NaN,0.174141,NaN,NaN,NaN,0.094367,NaN,-0.006157,0.571503,0.583669,0.210371,-0.487194,0.683867,0.627821,-0.806374,0.534712,-0.578547,NaN,NaN,1.837226,NaN,-0.065020,NaN,0.997340,-0.146856,NaN,0.400002,NaN,NaN,NaN,NaN,NaN,0.784194,0.128233,0.159639,0.880552,NaN,0.796170,NaN,NaN,NaN,-0.360163,NaN,1.304649,NaN,0.283098,0.444413,NaN,NaN,-1.148693,NaN,0.904476,NaN,NaN,NaN,NaN,NaN,NaN,0.086351,NaN,-2.425054,-1.026773,NaN,0.631330,0.401687,NaN,NaN,NaN,0.280907,NaN,NaN,NaN,NaN,-0.101824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.902046,NaN,-3.035207,-0.179229,NaN,NaN,NaN,NaN,-0.349017,NaN,NaN,NaN,0.632024,NaN,-0.375609,0.389729,0.548645,-0.125526,NaN,0.233990,NaN,1.614751,0.249856,NaN,NaN,0.579187,NaN,0.682630,NaN,-0.541720,NaN,-0.165147,-0.145705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.255807,NaN,-0.594467,-1.091301,NaN,0.295780,NaN,NaN,NaN,NaN,NaN,NaN,0.516208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.012660,0.649474,NaN,NaN,NaN,NaN,NaN,-0.058894,NaN,NaN,NaN,NaN,NaN,-0.873455,NaN,NaN,NaN,0.707783,0.071066,-0.364053,0.445052,0.581059,NaN,-1.661743,NaN,NaN,-0.743321,0.163870,NaN,NaN,NaN,NaN,NaN,0.436830,NaN,NaN,NaN,-0.521478,0.031790,NaN,0.499019,NaN,NaN,NaN,NaN,NaN,NaN,1.012951,NaN,NaN,0.580063,0.408595,NaN,NaN,NaN,1.380105,NaN,NaN,NaN,NaN,NaN,-2.120331,NaN,0.739933,NaN,0.308620,NaN,NaN,NaN,-0.082883,NaN,NaN,-0.131498,NaN,0.363687,-0.561158,NaN,0.125941,NaN,0.710811,0.613317,-0.451430,0.681097,NaN,NaN,NaN,NaN,NaN,NaN,-0.457655,NaN,-1.508167,NaN,NaN,-0.157391,NaN,0.201565,NaN,NaN,-0.899815,0.852415,0.639716,NaN,1.032879,NaN,-0.360232,NaN,NaN,NaN,NaN,-1.044533,NaN,NaN,NaN,NaN,NaN,-0.165368,NaN,NaN,0.558649,NaN,NaN,NaN,NaN,0.687682,0.978453,NaN,NaN,NaN,-1.448099,-0.096604,NaN,NaN,-0.326240,NaN,0.500325,NaN,NaN,NaN,NaN,NaN,1.057017,-0.944383,NaN,NaN,NaN,NaN,NaN,0.356115,1.729926,NaN,NaN,NaN,NaN,NaN,NaN,-0.440236,NaN,NaN,NaN,NaN,0.200213,0.560025,NaN,0.604916,0.023877,0.108138,NaN,NaN,NaN,0.439937,NaN,NaN,NaN,NaN,0.843318,NaN,-0.126091,-4.301310,0.446971,-2.003241,-1.248287,-0.541318,NaN,NaN,NaN,0.600587,0.669773,0.218326,0.558757,0.167709,-1.076268,NaN,-0.051765,NaN,NaN,NaN,NaN,2.117786,-0.035718,NaN,NaN,-0.525051,NaN,0.569851,NaN,NaN,0.336072,NaN,NaN,0.913732,NaN,-0.257995,0.843589,0.414841,NaN,-0.868053,-0.810562,NaN,NaN,NaN,NaN,-0.794066,NaN,NaN,NaN,NaN,NaN,0.883965,-1.755547,NaN,0.643956,0.604951,NaN,NaN,0.480918,-0.920882,0.750398,NaN,NaN,NaN,NaN,2.313309,0.538962,NaN,-0.299621,0.354080,NaN,-0.555652,NaN,-0.420425,NaN,NaN,NaN,NaN,-2.664192,NaN,0.624476,NaN,0.459532,0.497128,NaN,0.926127,NaN,NaN,NaN,NaN,0.375461,0.496609,-0.512370,NaN,NaN,NaN,NaN,-0.373498,NaN,-1.699489,-1.640192,NaN,-1.661804,NaN,NaN,NaN,NaN,-0.443588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.168384,NaN,NaN,NaN,1.107629,NaN,NaN,NaN,-0.099994,NaN,0.078063,NaN,NaN,1.040528,NaN,NaN,NaN,-0.631030,NaN,NaN,0.215083,NaN,NaN,NaN,1.035975,NaN,NaN,NaN,0.511751,-0.074439,-0.289977,NaN,NaN,0.419386,-0.765396,NaN,-1.704369,NaN,NaN,NaN,NaN,-3.841372,-0.801728,NaN,NaN,0.836213,NaN,NaN,NaN,NaN,NaN,-0.318761,NaN,0.266866,NaN,0.159607,NaN,NaN,NaN,NaN,-0.333117,NaN,-2.588330,0.287387,-0.183024,0.161233,NaN,NaN,NaN,NaN,-0.082464,NaN,0.986049,NaN,-1.437662,NaN,NaN,NaN,NaN,0.428722,NaN,NaN,NaN,NaN,NaN,-0.617743,NaN,0.093854,NaN,-0.152982,-2.313416,NaN,NaN,1.037880,0.074702,0.164180,NaN,NaN,NaN,1.057312,0.447412,0.024302,NaN,NaN,0.771564,0.773816,NaN,NaN,NaN,-1.026646,-0.011512,NaN,NaN,-0.000445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.981808,0.475503,NaN,0.169054,0.241792,NaN,NaN,NaN,0.796713,1.073139,NaN,NaN,NaN,0.187624,0.026168,-1.731890,NaN,NaN,NaN,-0.277412,-1.369700,NaN,NaN,NaN,0.031259,-0.639896,NaN,NaN,NaN,-1.676973,NaN,0.093868,0.717002,NaN,-0.125768,NaN,NaN,1.207397,-0.323890,NaN,NaN,NaN,0.621556,NaN,0.965143,NaN,0.289567,NaN,0.597169,1.133255,-0.244241,1.568232,NaN,0.256754,NaN,NaN,0.283930,-0.056521,NaN,NaN,-0.848044,NaN,NaN,NaN,NaN,1.114404,NaN,0.101305,0.154306,-0.377620,NaN,NaN,NaN,NaN,NaN,NaN,0.214882,-0.375349,NaN,0.755131,0.263145,0.854249,0.232079,NaN,0.385695,NaN,NaN,1.457770,NaN,1.001304,NaN,NaN,NaN,NaN,0.596842,2.871997,NaN,NaN,NaN,NaN,-0.880008,NaN,0.533132,0.128902,NaN,1.216046,NaN,1.316899,0.241313,-1.926158,NaN,NaN,NaN,NaN,-0.552906,-0.474386,NaN,0.538317,0.384248,NaN,-0.361392,NaN,NaN,0.590233,NaN,NaN,NaN,NaN,NaN,NaN,-0.364990,0.885646,NaN,NaN,NaN,0.018483,NaN,NaN,NaN,NaN,NaN,0.320385,-0.017918,NaN,NaN,NaN,NaN,NaN,0.454920,NaN,1.910102,0.832609,NaN,NaN,NaN,-0.396190,-0.622969,0.032649,NaN,-0.021887,NaN,NaN,-1.795408,0.370728,0.665712,NaN,0.530711,-0.316271,NaN,-0.090144,NaN,NaN,NaN,NaN,NaN,NaN,0.948045,-1.676618,NaN,0.230160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.587878,-3.236300,NaN,NaN,NaN,NaN,NaN,0.702622,NaN,-3.409252,NaN,0.350024,-1.667802,NaN,NaN,-1.276645,-1.483822,NaN,0.539501,0.727227,NaN,NaN,NaN,-0.596291,NaN,0.871573,-1.154679,NaN,NaN,-1.362296,NaN,NaN,0.264887,NaN,NaN,0.024399,0.018333,-0.511879,0.436853,NaN,NaN,0.636543,-1.108878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.778842,NaN,-1.333938,NaN,0.029609,NaN,NaN,NaN,0.328877,1.268641,NaN,NaN,NaN,-0.909656,NaN,NaN,NaN,NaN,NaN,0.051108,-0.215549,NaN,-0.516625,NaN,0.290144,0.718716,NaN,NaN,-0.588907,NaN,-0.803635,NaN,NaN,0.589758,NaN,NaN,0.427439,NaN,NaN,0.185895,NaN,0.750206,-0.095349,-0.097442,0.397558,NaN,NaN,-0.103842,-0.259527,NaN,NaN,NaN,-0.056211,NaN,NaN,NaN,0.536387,NaN,-0.483637,NaN,NaN,NaN,0.154926,-0.951886,NaN,0.842112,NaN,0.555923,NaN,0.400149,0.295593,NaN,NaN,0.193103,NaN,-0.299652,0.438398,NaN,-1.029880,-0.799016,NaN,NaN,NaN,-0.288488,NaN,NaN,NaN,NaN,-1.198857,-0.401561,-2.104238,NaN,NaN,NaN,-0.486876,-2.872989,NaN,NaN,NaN,0.378532,NaN,0.566092,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.602666,-0.184096,1.020406,0.727800,-4.990790,NaN,0.141671,NaN,NaN,NaN,NaN,NaN,-0.790859,NaN,0.104221,1.168941,-2.844326,NaN,0.345496,NaN,0.545898,-0.302664,-0.415848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.071679,0.691817,0.314290,NaN,NaN,NaN,-0.642756,NaN,NaN,0.796821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.184365,1.391185,NaN,NaN,NaN,NaN,-0.517261,NaN,NaN,-1.344764,NaN,NaN,NaN,NaN,NaN,NaN,0.596649,NaN,NaN,-0.909416,NaN,NaN,NaN,0.435974,NaN,NaN,NaN,NaN,NaN,0.562069,0.163110,1.454082,NaN,NaN,NaN,0.174257,0.400008,NaN,NaN,NaN,0.115568,-0.386717,NaN,NaN,NaN,0.245665,0.572181,0.719314,NaN,NaN,NaN,NaN,NaN,0.364227,NaN,-2.694556,0.220879,NaN,NaN,0.525422,NaN,0.130766,-0.453738,NaN,0.398395,NaN,NaN,-0.277712,NaN,NaN,NaN,0.496552,NaN,0.896174,NaN,0.073624,NaN,NaN,NaN,-0.237673,0.084674,NaN,-0.061557,0.906640,0.265792,NaN,NaN,NaN,0.180699,NaN,0.515582,NaN,NaN,NaN,NaN,NaN,0.073106,NaN,NaN,0.382144,NaN,NaN,NaN,-1.011413,NaN,NaN,-1.675817,NaN,-0.211643,0.393957,NaN,NaN,NaN,NaN,0.259009,-0.090767,-0.229390,NaN,NaN,NaN,0.051854,NaN,0.804294,NaN,0.495860,0.202138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.969083,-0.335042,1.018851,NaN,NaN,0.056808,-0.437539,NaN,0.050250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.626320,-3.415721,-0.026051,NaN,0.588622,-1.093827,NaN,NaN,-0.398489,NaN,-0.053723,0.673019,NaN,NaN,NaN,-0.100028,NaN,1.381557,NaN,NaN,0.632416,0.491136,NaN,NaN,-0.477544,NaN,NaN,NaN,NaN,0.103302,NaN,0.454961,-1.393144,NaN,NaN,NaN,0.840088,0.653221,1.158148,NaN,NaN,0.287088,0.022194,NaN,1.090222,-0.428893,NaN,NaN,NaN,NaN,0.430266,-0.560606,0.274977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.107918,NaN,0.262902,NaN,-1.830890,NaN,NaN,0.660255,-0.005268,-0.688633,-0.749495,0.173113,0.289171,NaN,-0.180687,NaN,NaN,NaN,-0.708053,0.358588,NaN,NaN,-0.593279,NaN,1.094937

## <font color=#0099CC>**5. SELECCIÓN MENSUAL DE LOS 20 ACTIVOS**</font>

### <font color=#336699>**5.1. Top 20 por score y peso 5 %**</font>

Cada mes se ordenan los activos del universo por score (mayor a menor) y se seleccionan los 20 primeros. A cada uno se asigna un peso objetivo del 5 % del capital disponible.

En el motor de backtest (Notebook 4) ese 5 % se aplica de forma aproximada por dos motivos: 
1) Solo se pueden comprar cantidades enteras de acciones, por lo que el valor de cada posición se redondea y no coincide exactamente con el 5 %.
2) Las ventas se ejecutan al precio de apertura y las compras al de cierre del día de rebalanceo, de modo que el capital realmente invertido en cada activo depende de esos precios y se desvía ligeramente del reparto teórico.

In [15]:
# Selección mensual de los 20 activos con mayor score

records = []

for dt, row in score.iterrows():
    # Filtramos NaN (fuera del universo o sin datos suficientes)
    row_valid = row.dropna()
    # Si ningún activo es elegible ese mes, se salta y no hay rebalanceo
    if row_valid.empty:
        continue

    # Ordena los activos de mayor a menor y selecciona los 20 mejores
    top20 = row_valid.nlargest(20)

    # Asigna ranking y pesos
    for rank, (symbol, sc) in enumerate(top20.items(), start=1):
        records.append(
            {
                'rebalance_date': dt,
                'rank': rank,
                'symbol': symbol,
                'score': sc,
                'weight': 0.05  # 5 % por activo seleccionado
            }
        )

# Convierte la lista de diccionarios en una tabla estructurada
selected_df = pd.DataFrame.from_records(records)

# Ordena y limpia
selected_df = selected_df.sort_values(['rebalance_date', 'rank']).reset_index(drop=True)

# Comprobación: ¿siempre hay 20 activos por rebalanceo?
counts = selected_df.groupby('rebalance_date').size()
n_per_date = counts.value_counts().sort_index()
print('> Selección mensual completada')
display(selected_df.tail())
print('> Comprobación nº activos por fecha de rebalanceo:')
print(f'  > Activos por mes: min={counts.min()}, max={counts.max()}, media={counts.mean():.2f}')
if (counts != 20).any():
    fechas_menos_20 = counts[counts != 20]
    print(f'  > Meses con distinto de 20 activos: {len(fechas_menos_20)}')
    display(fechas_menos_20.to_frame(name='n_activos'))
else:
    print('  > Todas las emisiones tienen exactamente 20 activos.')

> Selección mensual completada

     rebalance_date  rank symbol     score  weight
2635     2025-12-31    16   KLAC  1.873071    0.05
2636     2025-12-31    17   CHRW  1.720457    0.05
2637     2025-12-31    18   IDXX  1.693367    0.05
2638     2025-12-31    19    IVZ  1.626654    0.05
2639     2025-12-31    20    TPR  1.597688    0.05

> Comprobación nº activos por fecha de rebalanceo:
  > Activos por mes: min=20, max=20, media=20.00
  > Todas las emisiones tienen exactamente 20 activos.

> <u>Comentario</u>: La tabla muestra, por cada fecha de rebalanceo, el rango 1–20, el símbolo, el score y el peso. Este CSV es el insumo principal del Notebook 4 para ejecutar el backtest.

## <font color=#0099CC>**6. GUARDAR RESULTADOS**</font>

Se exportan: `selected_assets.csv` a `../outputs/` para el motor de backtest y `universe_mask_13m.parquet` a `../datasets/` como fuente de verdad del universo elegible para análisis posteriores (Monte Carlo en Notebook 5).

In [16]:
# Guardar resultados
os.makedirs(OUTPUTS_DIR, exist_ok=True)
os.makedirs(DATASETS_DIR, exist_ok=True)

# 1) Selección mensual para el motor de backtest
output_path = OUTPUTS_DIR / 'selected_assets.csv'
selected_df.to_csv(output_path, index=False)
print(f"> Archivo selected_assets.csv guardado: {output_path}")

# 2) Universo elegible mensual (fuente de verdad para análisis posteriores)
universe_path = DATASETS_DIR / 'universe_mask_13m.parquet'
universe_mask_bt.astype(bool).to_parquet(universe_path)
print(f"> Archivo universe_mask_13m.parquet guardado: {universe_path}")

> Archivo selected_assets.csv guardado: C:\Users\Javi\Desktop\backtesting\outputs\selected_assets.csv
> Archivo universe_mask_13m.parquet guardado: C:\Users\Javi\Desktop\backtesting\datasets\universe_mask_13m.parquet